import React, { useState } from 'react';
import { Wrench, Copy, Download, Printer, RotateCcw, ArrowLeft, FileText, Shield } from 'lucide-react';

export default function ChangeManagementPolicy() {
  const [formData, setFormData] = useState({
    orgName: '',
    policyPurpose: '',
    policyScope: '',
    roles: '',
    changeTypes: '',
    requestProcess: '',
    riskAssessment: '',
    implementationPlan: '',
    testingPlan: '',
    cabInfo: '',
    documentationRequirements: '',
    metrics: ''
  });

  const [output, setOutput] = useState('');

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const generatePolicy = () => {
    const policy = `
CHANGE MANAGEMENT POLICY
Organization: ${formData.orgName}

1. Purpose
${formData.policyPurpose}

2. Scope
${formData.policyScope}

3. Roles & Responsibilities
${formData.roles}

4. Types of Changes
${formData.changeTypes}

5. Change Request & Approval Process
${formData.requestProcess}

6. Risk & Impact Assessment
${formData.riskAssessment}

7. Implementation & Communication Plan
${formData.implementationPlan}

8. Testing & Validation
${formData.testingPlan}

9. Change Advisory Board (CAB)
${formData.cabInfo}

10. Documentation & Recordkeeping
${formData.documentationRequirements}

11. Metrics & Continuous Improvement
${formData.metrics}

Generated by CyberLifeCoach — Change Management Policy Generator
  `;

    setOutput(policy);
  };

  const resetAll = () => {
    setFormData({
      orgName: '',
      policyPurpose: '',
      policyScope: '',
      roles: '',
      changeTypes: '',
      requestProcess: '',
      riskAssessment: '',
      implementationPlan: '',
      testingPlan: '',
      cabInfo: '',
      documentationRequirements: '',
      metrics: ''
    });
    setOutput('');
  };

  const copyOutput = async () => {
    if (!output.trim()) {
      alert("Please generate a policy first.");
      return;
    }

    try {
      await navigator.clipboard.writeText(output);
      alert("Policy text copied to clipboard.");
    } catch (e) {
      alert("Copy failed. Please copy manually.");
    }
  };

  const downloadFile = (filename, mimeType) => {
    if (!output.trim()) {
      alert("Please generate a policy first.");
      return;
    }

    const blob = new Blob([output], { type: `${mimeType};charset=utf-8` });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const downloadText = () => {
    downloadFile("change-management-policy.txt", "text/plain");
  };

  const downloadMarkdown = () => {
    downloadFile("change-management-policy.md", "text/markdown");
  };

  const escapeHtml = (str) => {
    const map = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#039;"
    };
    return String(str).replace(/[&<>"']/g, m => map[m]);
  };

  const printOutput = () => {
    if (!output.trim()) {
      alert("Please generate a policy first.");
      return;
    }

    const win = window.open("", "_blank", "noopener,noreferrer");
    if (!win) {
      alert("Pop-up blocked. Please allow pop-ups to print/save as PDF.");
      return;
    }

    const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Change Management Policy</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #000; }
    h1 { font-size: 18px; margin: 0 0 16px; }
    pre { white-space: pre-wrap; word-wrap: break-word; font-family: "Courier New", monospace; font-size: 12px; line-height: 1.5; }
    @media print { body { margin: 20mm; } }
  </style>
</head>
<body>
  <h1>Change Management Policy</h1>
  <pre>${escapeHtml(output)}</pre>
  <script>
    window.onload = function() {
      window.focus();
      window.print();
      setTimeout(function() { window.close(); }, 300);
    };
  <\/script>
</body>
</html>`;

    win.document.open();
    win.document.write(html);
    win.document.close();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-slate-100">
      {/* Navigation */}
      <nav className="bg-slate-950/80 backdrop-blur-sm border-b border-slate-800 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            {/* Logo */}
<div className="flex items-center space-x-3 group cursor-pointer">
              <img 
                src="/logo.png" 
                alt="CyberLifeCoach" 
                className="h-10 w-auto group-hover:brightness-125 group-hover:scale-110 transition-all duration-300" 
              />
              <span className="text-xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent group-hover:brightness-125 transition-all duration-300">
                CyberLifeCoach
              </span>
            </div>

            {/* Back to Hub */}
            <button
              onClick={() => window.location.href = '/policy-generators'}
              className="flex items-center space-x-2 bg-slate-800 hover:bg-slate-700 px-4 py-2 rounded-lg transition-all duration-300 border border-slate-700 hover:border-cyan-500"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Business Policy Hub</span>
            </button>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 py-12">
        <div className="space-y-8">
          {/* Header */}
          <div className="text-center mb-12">
            <div className="flex items-center justify-center space-x-3 mb-4">
              <Wrench className="w-12 h-12 text-cyan-400" />
              <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">
                Change Management Policy Generator
              </h1>
            </div>
            <p className="text-xl text-slate-400 max-w-3xl mx-auto">
              Create a structured change management policy that documents how changes are requested, reviewed, approved, implemented, tested, and tracked across your systems and environments.
            </p>
          </div>

          {/* Security Badge */}
          <div className="bg-gradient-to-r from-cyan-900/30 to-blue-900/30 border border-cyan-500/30 rounded-xl p-4 max-w-2xl mx-auto">
            <div className="flex items-center justify-center space-x-3">
              <Shield className="w-6 h-6 text-cyan-400" />
              <span className="text-slate-300"><strong>Client-side only.</strong> Policy text is generated in your browser and not uploaded.</span>
            </div>
          </div>

          {/* Form Section */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-8">
            <h3 className="text-2xl font-bold mb-2 text-cyan-400">Policy Inputs</h3>
            <p className="text-slate-400 mb-6">
              Fill in the sections below. The generator will produce a structured change management policy draft that you can refine to match your organization processes.
            </p>

            <div className="space-y-6">
              {/* Organization Name */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Organization Name:
                </label>
                <textarea
                  name="orgName"
                  value={formData.orgName}
                  onChange={handleInputChange}
                  placeholder="Organization Name"
                  rows="2"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Purpose */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Purpose of the Change Management Policy:
                </label>
                <textarea
                  name="policyPurpose"
                  value={formData.policyPurpose}
                  onChange={handleInputChange}
                  placeholder="Purpose of the Change Management Policy"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Scope */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Scope (systems, teams, environments):
                </label>
                <textarea
                  name="policyScope"
                  value={formData.policyScope}
                  onChange={handleInputChange}
                  placeholder="Scope (systems, teams, environments)"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Roles and Responsibilities */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Roles and Responsibilities:
                </label>
                <textarea
                  name="roles"
                  value={formData.roles}
                  onChange={handleInputChange}
                  placeholder="Change Manager, Approvers, Requestors, Reviewers, Implementers, CAB roles"
                  rows="4"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Types of Changes */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Types of Changes:
                </label>
                <textarea
                  name="changeTypes"
                  value={formData.changeTypes}
                  onChange={handleInputChange}
                  placeholder="Standard, Normal, Emergency, Non-routine, Infrastructure, Application, etc."
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Request and Approval Process */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Request and Approval Process:
                </label>
                <textarea
                  name="requestProcess"
                  value={formData.requestProcess}
                  onChange={handleInputChange}
                  placeholder="Steps to request, evaluate, approve, reject, or defer a change"
                  rows="4"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Risk and Impact Assessment */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Risk and Impact Assessment:
                </label>
                <textarea
                  name="riskAssessment"
                  value={formData.riskAssessment}
                  onChange={handleInputChange}
                  placeholder="Impact criteria, risk scoring, business impact levels"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Implementation and Communication */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Implementation and Communication:
                </label>
                <textarea
                  name="implementationPlan"
                  value={formData.implementationPlan}
                  onChange={handleInputChange}
                  placeholder="Deployment process, communication needs, stakeholder notifications"
                  rows="4"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Testing and Validation */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Testing and Validation:
                </label>
                <textarea
                  name="testingPlan"
                  value={formData.testingPlan}
                  onChange={handleInputChange}
                  placeholder="Pre-change and post-change testing, QA steps, rollback validation"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Change Advisory Board (CAB) */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Change Advisory Board (CAB):
                </label>
                <textarea
                  name="cabInfo"
                  value={formData.cabInfo}
                  onChange={handleInputChange}
                  placeholder="CAB composition, meeting frequency, decision authority"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Documentation Requirements */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Documentation Requirements:
                </label>
                <textarea
                  name="documentationRequirements"
                  value={formData.documentationRequirements}
                  onChange={handleInputChange}
                  placeholder="Logs, approvals, test results, audit tracking"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Metrics and Continuous Improvement */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Metrics and Continuous Improvement:
                </label>
                <textarea
                  name="metrics"
                  value={formData.metrics}
                  onChange={handleInputChange}
                  placeholder="KPIs: change success rate, emergency changes, MTTR, backlog, etc."
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex flex-wrap gap-4 mt-8">
              <button
                onClick={generatePolicy}
                className="flex-1 min-w-[200px] bg-gradient-to-r from-cyan-500 to-blue-600 px-6 py-3 rounded-lg font-semibold hover:shadow-lg hover:shadow-cyan-500/50 transition-all duration-300 hover:scale-105 flex items-center justify-center space-x-2"
              >
                <FileText className="w-5 h-5" />
                <span>Generate Policy</span>
              </button>
              <button
                onClick={resetAll}
                className="flex-1 min-w-[200px] bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition-all duration-300 flex items-center justify-center space-x-2"
              >
                <RotateCcw className="w-5 h-5" />
                <span>Reset</span>
              </button>
            </div>
          </div>

          {/* Output Section */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-8">
            <h3 className="text-2xl font-bold mb-4 text-cyan-400">Generated Change Management Policy:</h3>
            <textarea
              value={output}
              readOnly
              placeholder="Your generated policy will appear here. Fill in the sections above, then select 'Generate Policy'. You can copy, download, or print the output."
              rows="20"
              className="w-full bg-slate-950 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 font-mono text-sm resize-none"
            />

            {/* Download Buttons */}
            <div className="flex flex-wrap gap-4 mt-6">
              <button
                onClick={copyOutput}
                className="flex items-center space-x-2 bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition-all duration-300"
              >
                <Copy className="w-5 h-5" />
                <span>Copy</span>
              </button>
              <button
                onClick={downloadText}
                className="flex items-center space-x-2 bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition-all duration-300"
              >
                <Download className="w-5 h-5" />
                <span>Download TXT</span>
              </button>
              <button
                onClick={downloadMarkdown}
                className="flex items-center space-x-2 bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition-all duration-300"
              >
                <Download className="w-5 h-5" />
                <span>Download Markdown</span>
              </button>
              <button
                onClick={printOutput}
                className="flex items-center space-x-2 bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition-all duration-300"
              >
                <Printer className="w-5 h-5" />
                <span>Print/Save as PDF</span>
              </button>
            </div>

            <p className="text-sm text-slate-500 mt-4">Tip: Print/Save as PDF uses your browser print dialog. Choose Save as PDF.</p>
          </div>

          {/* Legal Disclaimer */}
          <div className="mt-8 bg-slate-900/50 border border-slate-700 rounded-xl p-6">
            <p className="text-sm text-slate-400 leading-relaxed">
              <strong className="text-cyan-400">Important notice:</strong> This change management policy generator provides sample structure and wording for informational and educational purposes. It does not constitute legal, regulatory, or compliance advice. You are responsible for ensuring the resulting policy aligns with your organization requirements, applicable laws and regulations, and operational needs. Text is generated locally in your browser and is not transmitted to external servers.
            </p>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-slate-950 border-t border-slate-800 py-12 px-4">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <img 
              src="/logo.png" 
              alt="CyberLifeCoach" 
              className="h-8 w-auto transition-all duration-300 hover:scale-125 hover:brightness-125" 
            />
            <span className="font-bold text-lg transition-all duration-300 hover:text-cyan-400 hover:drop-shadow-[0_0_15px_rgba(34,211,238,0.8)]">
              CyberLifeCoach
            </span>
          </div>
          <div className="text-slate-500 text-sm">
            <p>&copy; 2026 CyberLifeCoach</p>
            <p className="text-slate-600">A Veteran-Owned Business Committed to Your Digital Security</p>
            <p>All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
