import React, { useState } from 'react';
import { Lock, Copy, Download, Printer, RotateCcw, ArrowLeft, FileText, GraduationCap } from 'lucide-react';

export default function SecurityAwarenessPolicy() {
  const [formData, setFormData] = useState({
    orgName: '',
    policyPurpose: '',
    policyScope: '',
    audience: '',
    trainingCadence: '',
    deliveryMethods: '',
    requiredTopics: '',
    roleBasedTraining: '',
    phishingProgram: '',
    reportingProcess: '',
    rolesResponsibilities: '',
    trackingEvidence: '',
    nonCompliance: '',
    privacyHandling: '',
    reviewCadence: '',
    references: ''
  });

  const [output, setOutput] = useState('');

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const generatePolicy = () => {
    const {
      orgName,
      policyPurpose,
      policyScope,
      audience,
      trainingCadence,
      deliveryMethods,
      requiredTopics,
      roleBasedTraining,
      phishingProgram,
      reportingProcess,
      rolesResponsibilities,
      trackingEvidence,
      nonCompliance,
      privacyHandling,
      reviewCadence,
      references
    } = formData;

    const output = `
SECURITY AWARENESS TRAINING POLICY
Organization: ${orgName || "[Organization Name]"}

1. Purpose
${policyPurpose || "[Describe the purpose of the security awareness training program and the outcomes it supports.]"}

2. Scope
${policyScope || "[Define the scope, including which teams, systems, locations, or environments are covered.]"}

3. Covered Population
${audience || "[Identify who must complete training, including employees, contractors, interns, and third parties with access.]"}

4. Training Requirements and Cadence
${trainingCadence || "[Define onboarding timing and recurring cadence, plus triggers for additional training after incidents or role changes.]"}

5. Delivery Methods
${deliveryMethods || "[Describe how training is delivered, including LMS modules, live sessions, tabletop exercises, and micro learning.]"}

6. Required Topics
${requiredTopics || "[List required training topics, including phishing, social engineering, password and MFA practices, safe browsing, device security, and data handling.]"}

7. Role Based Training
${roleBasedTraining || "[Define additional training for higher risk roles, such as privileged access users, finance, HR, developers, and executives.]"}

8. Phishing Simulations and Practical Exercises
${phishingProgram || "[Describe simulation frequency, feedback and coaching, retesting, and how results are used to improve training.]"}

9. Reporting Suspicious Activity
${reportingProcess || "[Provide clear reporting instructions and expected response timelines, including how to report phishing, lost devices, and suspicious behavior.]"}

10. Roles and Responsibilities
${rolesResponsibilities || "[Define responsibilities for security, IT, HR, managers, and individual users.]"}

11. Tracking, Evidence, and Completion
${trackingEvidence || "[Explain how completion is tracked, how attestations are collected, and what evidence is retained for audits.]"}

12. Non Compliance and Remediation
${nonCompliance || "[Describe reminders and escalation, corrective training, and any temporary access restrictions for missed deadlines.]"}

13. Privacy and Data Handling in Training
${privacyHandling || "[Describe what training data is collected, who can access it, retention periods, and safeguards for protecting training records.]"}

14. Policy Review and Updates
${reviewCadence || "[Define review frequency and update triggers, including major incidents, business changes, and new regulatory requirements.]"}

15. References and Alignment
${references || "[List internal references and optional external frameworks that inform the program, such as NIST and ISO guidance.]"}

Generated by the CyberLife Coach – Security Awareness Training Policy Generator
    `.trim();

    setOutput(output);
  };

  const resetForm = () => {
    setFormData({
      orgName: '',
      policyPurpose: '',
      policyScope: '',
      audience: '',
      trainingCadence: '',
      deliveryMethods: '',
      requiredTopics: '',
      roleBasedTraining: '',
      phishingProgram: '',
      reportingProcess: '',
      rolesResponsibilities: '',
      trackingEvidence: '',
      nonCompliance: '',
      privacyHandling: '',
      reviewCadence: '',
      references: ''
    });
    setOutput('');
  };

  const copyOutput = async () => {
    if (!output) {
      alert("There is no generated policy to copy yet.");
      return;
    }

    try {
      await navigator.clipboard.writeText(output);
      alert("Policy text copied to clipboard.");
    } catch (e) {
      alert("Copy failed. Please copy manually.");
    }
  };

  const downloadFile = (filename, content) => {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const downloadText = () => {
    if (!output) {
      alert("There is no generated policy to download yet.");
      return;
    }
    downloadFile('security-awareness-training-policy.txt', output);
  };

  const downloadMarkdown = () => {
    if (!output) {
      alert("There is no generated policy to download yet.");
      return;
    }
    downloadFile('security-awareness-training-policy.md', output);
  };

  const printOutput = () => {
    if (!output) {
      alert("There is no generated policy to print yet.");
      return;
    }

    const printWindow = window.open('', '_blank', 'width=900,height=700');
    if (!printWindow) {
      alert("Pop-up blocked. Please allow pop-ups to print/save as PDF.");
      return;
    }

    const escapeHtml = (str) => {
      return String(str).replace(/</g, '&lt;').replace(/>/g, '&gt;');
    };

    printWindow.document.write(`
      <html>
      <head>
        <title>Security Awareness Training Policy</title>
        <style>
          body {
            font-family: system-ui, -apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif;
            padding: 24px;
            color: #020617;
            background: #ffffff;
            white-space: pre-wrap;
          }
        </style>
      </head>
      <body>${escapeHtml(output)}</body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-white">
      {/* Navigation */}
      <nav className="bg-slate-950/80 backdrop-blur-md border-b border-slate-800 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
<div className="flex items-center space-x-3 group cursor-pointer">
              <img 
                src="/logo.png" 
                alt="CyberLifeCoach" 
                className="h-10 w-auto group-hover:brightness-125 group-hover:scale-110 transition-all duration-300" 
              />
              <span className="text-xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent group-hover:brightness-125 transition-all duration-300">
                CyberLifeCoach
              </span>
            </div>
          <button
            onClick={() => window.location.href = '/policy-generators'}
            className="flex items-center space-x-2 bg-slate-800 hover:bg-slate-700 px-4 py-2 rounded-lg transition-all duration-300"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Business Policy Hub</span>
          </button>
        </div>
      </nav>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 py-12">
        <div className="space-y-8">
          {/* Header */}
          <div className="text-center mb-12">
            <div className="flex items-center justify-center space-x-3 mb-4">
              <GraduationCap className="w-12 h-12 text-cyan-400" />
              <h1 className="text-5xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">
                Security Awareness Training Policy Generator
              </h1>
            </div>
            <p className="text-xl text-slate-400 max-w-3xl mx-auto">
              Create a practical security awareness training policy that defines required training, topics, cadence,
              reporting expectations, and proof of completion for staff and contractors.
            </p>
          </div>

          {/* Security Badge */}
          <div className="bg-gradient-to-r from-cyan-500/10 to-blue-500/10 border border-cyan-500/30 rounded-xl p-4 flex items-center justify-center space-x-3">
            <Lock className="w-6 h-6 text-cyan-400" />
            <span className="text-slate-300"><strong>Client-side only.</strong> Policy text is generated in your browser and not uploaded.</span>
          </div>

          {/* Form Section */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-8">
            <h3 className="text-2xl font-bold text-cyan-400 mb-2">Policy Inputs</h3>
            <p className="text-slate-400 mb-6">
              Fill in the sections below. The generator will produce a structured security awareness training policy draft
              that you can refine for your organization.
            </p>

            <div className="space-y-6">
              {/* Organization Name */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Organization Name
                </label>
                <textarea
                  name="orgName"
                  value={formData.orgName}
                  onChange={handleInputChange}
                  placeholder="Organization Name"
                  rows="2"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Purpose */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Purpose
                </label>
                <textarea
                  name="policyPurpose"
                  value={formData.policyPurpose}
                  onChange={handleInputChange}
                  placeholder="Why this training policy exists and what outcomes it supports"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Scope */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Scope
                </label>
                <textarea
                  name="policyScope"
                  value={formData.policyScope}
                  onChange={handleInputChange}
                  placeholder="Teams, systems, and environments covered by this policy"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Covered Population */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Covered Population
                </label>
                <textarea
                  name="audience"
                  value={formData.audience}
                  onChange={handleInputChange}
                  placeholder="Employees, contractors, interns, vendors with access, remote staff, etc."
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Training Cadence */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Training Cadence
                </label>
                <textarea
                  name="trainingCadence"
                  value={formData.trainingCadence}
                  onChange={handleInputChange}
                  placeholder="Onboarding timing and recurring cadence, for example annually, quarterly, role based"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Delivery Methods */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Delivery Methods
                </label>
                <textarea
                  name="deliveryMethods"
                  value={formData.deliveryMethods}
                  onChange={handleInputChange}
                  placeholder="LMS, live sessions, tabletop exercises, micro learning, newsletters, etc."
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Required Topics */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Required Topics
                </label>
                <textarea
                  name="requiredTopics"
                  value={formData.requiredTopics}
                  onChange={handleInputChange}
                  placeholder="Phishing, password hygiene, MFA, device security, data handling, social engineering, incident reporting, etc."
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Role Based Training */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Role Based Training
                </label>
                <textarea
                  name="roleBasedTraining"
                  value={formData.roleBasedTraining}
                  onChange={handleInputChange}
                  placeholder="Additional training for privileged users, finance, HR, developers, customer support, executives, etc."
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Phishing Simulations */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Phishing Simulations and Exercises
                </label>
                <textarea
                  name="phishingProgram"
                  value={formData.phishingProgram}
                  onChange={handleInputChange}
                  placeholder="Simulation frequency, coaching workflow, retesting, and what success looks like"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Reporting Suspicious Activity */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Reporting Suspicious Activity
                </label>
                <textarea
                  name="reportingProcess"
                  value={formData.reportingProcess}
                  onChange={handleInputChange}
                  placeholder="How to report suspected phishing, lost devices, or suspicious activity, include channels and response expectations"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Roles and Responsibilities */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Roles and Responsibilities
                </label>
                <textarea
                  name="rolesResponsibilities"
                  value={formData.rolesResponsibilities}
                  onChange={handleInputChange}
                  placeholder="Security team, HR, managers, IT, training owners, employees, etc."
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Tracking and Evidence */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Tracking, Evidence, and Completion Requirements
                </label>
                <textarea
                  name="trackingEvidence"
                  value={formData.trackingEvidence}
                  onChange={handleInputChange}
                  placeholder="How completion is tracked, required attestations, and audit evidence"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Non-Compliance */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Non Compliance and Remediation
                </label>
                <textarea
                  name="nonCompliance"
                  value={formData.nonCompliance}
                  onChange={handleInputChange}
                  placeholder="Reminders, escalation path, temporary access restrictions, corrective actions"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Privacy Handling */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Privacy and Data Handling in Training
                </label>
                <textarea
                  name="privacyHandling"
                  value={formData.privacyHandling}
                  onChange={handleInputChange}
                  placeholder="What training data is collected, who can see it, retention, and how it is protected"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* Review Cadence */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  Policy Review and Updates
                </label>
                <textarea
                  name="reviewCadence"
                  value={formData.reviewCadence}
                  onChange={handleInputChange}
                  placeholder="Review frequency, update triggers, and how changes are communicated"
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>

              {/* References */}
              <div>
                <label className="block text-sm font-semibold text-cyan-400 mb-2">
                  References and Alignment
                </label>
                <textarea
                  name="references"
                  value={formData.references}
                  onChange={handleInputChange}
                  placeholder="Internal standards, plus optional references such as NIST SP 800-50, NIST CSF, ISO 27001, HIPAA, PCI DSS, etc."
                  rows="3"
                  className="w-full bg-slate-800 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 resize-none"
                />
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex flex-wrap gap-4 mt-8">
              <button
                onClick={generatePolicy}
                className="flex-1 min-w-[200px] bg-gradient-to-r from-cyan-500 to-blue-600 px-6 py-3 rounded-lg font-semibold hover:shadow-lg hover:shadow-cyan-500/50 transition-all duration-300 hover:scale-105 flex items-center justify-center space-x-2"
              >
                <FileText className="w-5 h-5" />
                <span>Generate Policy</span>
              </button>
              <button
                onClick={resetForm}
                className="flex-1 min-w-[200px] bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition-all duration-300 flex items-center justify-center space-x-2"
              >
                <RotateCcw className="w-5 h-5" />
                <span>Reset</span>
              </button>
            </div>
          </div>

          {/* Output Section */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-8">
            <h3 className="text-2xl font-bold mb-4 text-cyan-400">Generated Security Awareness Training Policy</h3>
            <textarea
              value={output}
              readOnly
              placeholder="Your generated policy will appear here. Fill in the sections on the left, then select 'Generate Policy'. You can copy, download, or print the output."
              rows="20"
              className="w-full bg-slate-950 border border-slate-600 rounded-lg px-4 py-3 focus:outline-none focus:border-cyan-500 transition-colors text-slate-100 font-mono text-sm resize-none"
            />

            {/* Download Buttons */}
            <div className="flex flex-wrap gap-4 mt-6">
              <button
                onClick={copyOutput}
                className="flex items-center space-x-2 bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition-all duration-300"
              >
                <Copy className="w-5 h-5" />
                <span>Copy</span>
              </button>
              <button
                onClick={downloadText}
                className="flex items-center space-x-2 bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition-all duration-300"
              >
                <Download className="w-5 h-5" />
                <span>Download TXT</span>
              </button>
              <button
                onClick={downloadMarkdown}
                className="flex items-center space-x-2 bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition-all duration-300"
              >
                <Download className="w-5 h-5" />
                <span>Download Markdown</span>
              </button>
              <button
                onClick={printOutput}
                className="flex items-center space-x-2 bg-slate-700 hover:bg-slate-600 px-6 py-3 rounded-lg font-semibold transition-all duration-300"
              >
                <Printer className="w-5 h-5" />
                <span>Print/Save as PDF</span>
              </button>
            </div>

            <p className="text-sm text-slate-500 mt-4">Tip: Print/Save as PDF uses your browser print dialog. Choose Save as PDF.</p>
          </div>

          {/* Legal Disclaimer */}
          <div className="mt-8 bg-slate-900/50 border border-slate-700 rounded-xl p-6">
            <p className="text-sm text-slate-400 leading-relaxed">
              <strong className="text-cyan-400">Important notice:</strong> This security awareness training policy generator provides sample structure and wording for informational and educational purposes. It does not constitute legal advice, compliance guidance, or a comprehensive security program. Organizations must tailor content to their specific environment, regulatory obligations, and risk profile. Consult qualified legal, compliance, and security professionals to ensure your training policy meets applicable requirements.
            </p>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-slate-950 border-t border-slate-800 py-12 px-4">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <img 
              src="/logo.png" 
              alt="CyberLifeCoach" 
              className="h-8 w-auto transition-all duration-300 hover:scale-125 hover:brightness-125" 
            />
            <span className="font-bold text-lg transition-all duration-300 hover:text-cyan-400 hover:drop-shadow-[0_0_15px_rgba(34,211,238,0.8)]">
              CyberLifeCoach
            </span>
          </div>
          <div className="text-slate-500 text-sm">
            <p>&copy; 2026 CyberLifeCoach</p>
            <p className="text-slate-600">A Veteran-Owned Business Committed to Your Digital Security</p>
            <p>All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
