import React, { useState, useEffect } from 'react';
import { Shield, ArrowLeft, Copy, Download, Trash2, Settings, AlertTriangle, CheckCircle, Info } from 'lucide-react';

export default function FirewallBaselineMacOS() {
  const [selectedControls, setSelectedControls] = useState({
    enableFw: true,
    blockAll: true,
    stealthLog: true,
    disableSigned: true,
    backup: true
  });
  const [scriptOutput, setScriptOutput] = useState('');
  const [downloadFormat, setDownloadFormat] = useState('sh');

  // Control definitions
  const controls = [
    {
      key: 'enableFw',
      title: 'Enable the native Application Firewall',
      description: 'Turns on the macOS Application Firewall so inbound connections are governed by system policy instead of being left open.',
      badge: 'Required',
      badgeColor: 'cyan'
    },
    {
      key: 'blockAll',
      title: 'Enforce default-deny inbound (block all)',
      description: 'Enables the "block all incoming connections" setting so unsolicited inbound traffic is denied unless explicitly allowed.',
      badge: 'Strict posture',
      badgeColor: 'yellow'
    },
    {
      key: 'stealthLog',
      title: 'Enable stealth mode and logging',
      description: 'Makes the system quieter on the network while still recording firewall events so you retain visibility for audits and troubleshooting.',
      badge: 'Recommended',
      badgeColor: 'cyan'
    },
    {
      key: 'disableSigned',
      title: 'Disable automatic allow rules for signed apps',
      description: 'Turns off automatic allow behavior for Apple-signed and downloaded signed apps, nudging the firewall toward explicit policy rather than implicit trust.',
      badge: null,
      badgeColor: null
    },
    {
      key: 'backup',
      title: 'Create backups and support rollback',
      description: 'Exports the current firewall plist to a timestamped backup under /usr/local/macos-firewall-backups and provides a rollback function to restore the most recent copy.',
      badge: null,
      badgeColor: null
    }
  ];

  useEffect(() => {
    generateScript();
  }, []);

  const handleControlToggle = (key) => {
    const newSelection = { ...selectedControls, [key]: !selectedControls[key] };
    setSelectedControls(newSelection);
  };

  const clearAll = () => {
    const newSelection = {};
    controls.forEach(control => {
      newSelection[control.key] = false;
    });
    setSelectedControls(newSelection);
    generateScript(newSelection);
  };

  const generateScript = (selection = selectedControls) => {
    const script = buildScript(selection);
    setScriptOutput(script);
  };

  const buildScript = (options) => {
    const enableFw = !!options.enableFw;
    const blockAll = !!options.blockAll;
    const stealthLog = !!options.stealthLog;
    const disableSigned = !!options.disableSigned;
    const includeBackup = !!options.backup;

    const lines = [];

    // Check if nothing is selected
    if (!enableFw && !blockAll && !stealthLog && !disableSigned && !includeBackup) {
      lines.push('# No macOS firewall controls were selected when this script was generated.');
      lines.push('# Select at least one control and generate the script again.');
      return lines.join('\n');
    }

    lines.push('#!/bin/bash');
    lines.push('#');
    lines.push('# macos_firewall_stig.sh');
    lines.push('# Harden the macOS Application Firewall in a STIG-style configuration.');
    lines.push('#');
    lines.push('# Generated by macOS Firewall Baseline Script Assistant – CyberLife Coach');
    lines.push('# Review every line before running. Test on a non-critical system first.');
    lines.push('#');
    lines.push('# Actions:');

    if (includeBackup) {
      lines.push('#   1) Optional: Backup current firewall plist');
    }
    if (enableFw) {
      lines.push('#   2) Enable Application Firewall');
    }
    if (blockAll) {
      lines.push('#   3) Enforce a default-deny posture ("block all" inbound)');
    }
    if (stealthLog) {
      lines.push('#   4) Enable stealth mode and logging');
    }
    if (disableSigned) {
      lines.push('#   5) Disable automatic allow rules for signed / built-in apps');
    }

    lines.push('#');
    lines.push('# Usage:');
    lines.push('#   sudo ./macos_firewall_stig.sh apply');
    if (includeBackup) {
      lines.push('#   sudo ./macos_firewall_stig.sh rollback');
    }
    lines.push('');
    lines.push('set -euo pipefail');
    lines.push('');

    if (includeBackup) {
      lines.push('BACKUP_DIR="/usr/local/macos-firewall-backups"');
      lines.push('PLIST_PATH="/Library/Preferences/com.apple.alf.plist"');
      lines.push('');
    }

    lines.push('FW_BIN="/usr/libexec/ApplicationFirewall/socketfilterfw"');
    lines.push('');
    lines.push('log() {');
    lines.push('  echo "[$(date "+%F %T")] $*"');
    lines.push('}');
    lines.push('');
    lines.push('err() {');
    lines.push('  echo "[$(date "+%F %T")] ERROR: $*" >&2');
    lines.push('}');
    lines.push('');
    lines.push('require_root() {');
    lines.push('  if [[ $EUID -ne 0 ]]; then');
    lines.push('    err "This script must be run as root. Rerun with sudo."');
    lines.push('    exit 1');
    lines.push('  fi');
    lines.push('}');
    lines.push('');
    lines.push('check_prereqs() {');
    lines.push('  if [[ ! -x "$FW_BIN" ]]; then');
    lines.push('    err "Cannot find socketfilterfw at $FW_BIN."');
    lines.push('    err "This script is designed for macOS systems with the Application Firewall."');
    lines.push('    exit 1');
    lines.push('  fi');
    lines.push('}');
    lines.push('');

    if (includeBackup) {
      lines.push('backup_current_plist() {');
      lines.push('  log "Backing up current firewall configuration..."');
      lines.push('');
      lines.push('  if [[ ! -d "$BACKUP_DIR" ]]; then');
      lines.push('    mkdir -p "$BACKUP_DIR" || {');
      lines.push('      err "Failed to create backup directory at $BACKUP_DIR."');
      lines.push('      exit 1');
      lines.push('    }');
      lines.push('  fi');
      lines.push('');
      lines.push('  if [[ ! -f "$PLIST_PATH" ]]; then');
      lines.push('    log "No existing firewall plist at $PLIST_PATH. Skipping backup."');
      lines.push('    return');
      lines.push('  fi');
      lines.push('');
      lines.push('  local timestamp');
      lines.push('  timestamp="$(date +%Y%m%d_%H%M%S)"');
      lines.push('  local backup_file="$BACKUP_DIR/com.apple.alf.$timestamp.plist"');
      lines.push('');
      lines.push('  cp "$PLIST_PATH" "$backup_file" || {');
      lines.push('    err "Failed to copy plist to $backup_file."');
      lines.push('    exit 1');
      lines.push('  }');
      lines.push('');
      lines.push('  log "Backup saved to: $backup_file"');
      lines.push('}');
      lines.push('');
    }

    lines.push('apply_hardening() {');
    lines.push('  log "Applying macOS firewall hardening..."');
    lines.push('');

    if (enableFw || blockAll || stealthLog || disableSigned) {
      if (enableFw) {
        lines.push('  log "Enabling Application Firewall..."');
        lines.push('  "$FW_BIN" --setglobalstate on');
        lines.push('');
      }
      if (blockAll) {
        lines.push('  log "Enabling block-all mode (denying unsolicited inbound connections)..."');
        lines.push('  "$FW_BIN" --setblockall on');
        lines.push('');
      }
      if (stealthLog) {
        lines.push('  log "Enabling stealth mode (do not respond to unsolicited probes)..."');
        lines.push('  "$FW_BIN" --setstealthmode on');
        lines.push('');
        lines.push('  log "Enabling firewall logging..."');
        lines.push('  "$FW_BIN" --setloggingmode on');
        lines.push('');
      }
      if (disableSigned) {
        lines.push('  log "Disabling auto-allow for signed Apple binaries..."');
        lines.push('  "$FW_BIN" --setallowsigned off');
        lines.push('');
        lines.push('  log "Disabling auto-allow for downloaded signed apps..."');
        lines.push('  "$FW_BIN" --setallowsignedapp off');
        lines.push('');
      }

      lines.push('  log "Restarting firewall service so changes take effect..."');
      lines.push('  # The service will be relaunched by the system');
      lines.push('  pkill socketfilterfw 2>/dev/null || true');
      lines.push('');
      lines.push('  log "Firewall hardening completed."');
      if (blockAll) {
        lines.push('  log "Reminder: This configuration is strict and may break inbound services like file sharing or remote management."');
      }
    }

    lines.push('}');
    lines.push('');

    if (includeBackup) {
      lines.push('rollback_latest_backup() {');
      lines.push('  if [[ ! -d "$BACKUP_DIR" ]]; then');
      lines.push('    err "No backup directory at $BACKUP_DIR. Nothing to roll back to."');
      lines.push('    exit 1');
      lines.push('  fi');
      lines.push('');
      lines.push('  local latest');
      lines.push('  latest="$(ls -1t "$BACKUP_DIR"/com.apple.alf.*.plist 2>/dev/null | head -n 1 || true)"');
      lines.push('');
      lines.push('  if [[ -z "$latest" ]]; then');
      lines.push('    err "No backup plist files found in $BACKUP_DIR."');
      lines.push('    exit 1');
      lines.push('  fi');
      lines.push('');
      lines.push('  log "Restoring firewall settings from:"');
      lines.push('  log "  $latest"');
      lines.push('');
      lines.push('  defaults import "$PLIST_PATH" "$latest" || {');
      lines.push('    err "Failed to import backup plist. Aborting rollback."');
      lines.push('    exit 1');
      lines.push('  }');
      lines.push('');
      lines.push('  log "Restarting firewall service to apply restored settings..."');
      lines.push('  pkill socketfilterfw 2>/dev/null || true');
      lines.push('');
      lines.push('  log "Rollback completed. Previous firewall configuration has been restored."');
      lines.push('}');
      lines.push('');
    }

    lines.push('print_summary() {');
    lines.push('  log "Current firewall state:"');
    lines.push('  "$FW_BIN" --getglobalstate || true');
    lines.push('  "$FW_BIN" --getblockall || true');
    lines.push('  "$FW_BIN" --getstealthmode || true');
    lines.push('  "$FW_BIN" --getloggingmode || true');
    lines.push('  "$FW_BIN" --getallowsigned || true');
    lines.push('  "$FW_BIN" --getallowsignedapp || true');
    lines.push('}');
    lines.push('');
    lines.push('usage() {');
    lines.push('  cat <<EOF');
    lines.push('Usage: sudo $0 [apply' + (includeBackup ? '|rollback' : '') + ']');
    lines.push('');
    if (enableFw || blockAll || stealthLog || disableSigned) {
      lines.push('  apply      Apply the selected macOS firewall baseline settings.');
    } else {
      lines.push('  apply      No firewall controls were selected at generation time. This will be a no-op.');
    }
    if (includeBackup) {
      lines.push('  rollback   Restore the most recent firewall backup from:');
      lines.push('             $BACKUP_DIR');
    }
    lines.push('');
    lines.push('Examples:');
    if (enableFw || blockAll || stealthLog || disableSigned) {
      lines.push('  sudo $0 apply');
    }
    if (includeBackup) {
      lines.push('  sudo $0 rollback');
    }
    lines.push('EOF');
    lines.push('}');
    lines.push('');
    lines.push('main() {');
    lines.push('  local action="${1:-}"');
    lines.push('');
    lines.push('  if [[ -z "$action" ]]; then');
    lines.push('    usage');
    lines.push('    exit 1');
    lines.push('  fi');
    lines.push('');
    lines.push('  require_root "$@"');
    lines.push('  check_prereqs');
    lines.push('');
    lines.push('  case "$action" in');
    lines.push('    apply)');
    lines.push('      log "You are about to apply a macOS firewall configuration generated by this baseline assistant."');
    if (blockAll) {
      lines.push('      log "It may block inbound services such as file sharing, AirDrop reception, or remote admin."');
    }
    lines.push('      read -r -p "Continue? [y/N]: " answer');
    lines.push('      answer="${answer:-N}"');
    lines.push('');
    lines.push('      if [[ "$answer" != "y" && "$answer" != "Y" ]]; then');
    lines.push('        log "Aborting at user request."');
    lines.push('        exit 0');
    lines.push('      fi');
    lines.push('');
    if (includeBackup) {
      lines.push('      backup_current_plist');
    }
    lines.push('      apply_hardening');
    lines.push('      print_summary');
    lines.push('      ;;');
    lines.push('');
    if (includeBackup) {
      lines.push('    rollback)');
      lines.push('      rollback_latest_backup');
      lines.push('      print_summary');
      lines.push('      ;;');
      lines.push('');
    }
    lines.push('    *)');
    lines.push('      err "Unknown action: $action"');
    lines.push('      usage');
    lines.push('      exit 1');
    lines.push('      ;;');
    lines.push('  esac');
    lines.push('}');
    lines.push('');
    lines.push('main "$@"');
    lines.push('');

    return lines.join('\n');
  };

  const copyToClipboard = () => {
    if (scriptOutput) {
      navigator.clipboard.writeText(scriptOutput).catch(err => {
        console.warn('Clipboard write failed:', err);
      });
    }
  };

  const downloadScript = () => {
    if (!scriptOutput.trim()) return;

    const extension = downloadFormat === 'txt' ? 'txt' : 'sh';
    const blob = new Blob([scriptOutput], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `macos-firewall-baseline.${extension}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getBadgeColor = (color) => {
    switch (color) {
      case 'cyan':
        return 'border-cyan-500/40 bg-cyan-500/10 text-cyan-400';
      case 'yellow':
        return 'border-yellow-500/40 bg-yellow-500/10 text-yellow-400';
      default:
        return 'border-slate-500/40 bg-slate-500/10 text-slate-300';
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-slate-100">
      {/* Navigation */}
      <nav className="fixed w-full z-50 bg-slate-900/95 backdrop-blur-sm shadow-lg">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-20">
            <a href="/security-center" className="flex items-center space-x-3 group cursor-pointer">
              <img 
                src="/logo.png" 
                alt="CyberLifeCoach" 
                className="h-10 w-auto group-hover:brightness-125 group-hover:scale-110 transition-all duration-300" 
              />
              <span className="text-xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent group-hover:brightness-125 transition-all duration-300">
                CyberLifeCoach
              </span>
            </a>

            <a href="/security-center/firewall-hardening-hub" className="flex items-center space-x-2 text-slate-300 hover:text-cyan-400 transition-colors">
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Firewall Hardening Hub</span>
            </a>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-32 pb-12 px-4 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-cyan-950/20 to-transparent"></div>
        <div className="absolute inset-0 opacity-20">
          <div className="absolute top-20 left-10 w-72 h-72 bg-cyan-500 rounded-full filter blur-3xl animate-pulse"></div>
        </div>
        
        <div className="relative max-w-7xl mx-auto">
          <div className="flex flex-wrap gap-2 mb-4">
            <span className="text-xs px-3 py-1 rounded-full bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 uppercase tracking-wider">
              Security Baseline Script Assistant
            </span>
            <span className="text-xs px-3 py-1 rounded-full bg-slate-700/50 text-slate-300 border border-slate-600">
              macOS Firewall
            </span>
            <span className="text-xs px-3 py-1 rounded-full bg-slate-700/50 text-slate-300 border border-slate-600">
              Local, in-browser helper
            </span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-cyan-400 to-blue-400 bg-clip-text text-transparent">
            Generate a macOS firewall baseline script in a few clicks
          </h1>
          <p className="text-lg text-slate-400 max-w-3xl">
            This assistant prepares a Bash script that hardens the native macOS Application Firewall toward a STIG-style baseline. The script enables the firewall, enforces a default-deny inbound posture, enables stealth mode and logging, and adds a simple backup and rollback path for your existing settings. No data leaves your browser.
          </p>
        </div>
      </section>

      {/* Main Content */}
      <section className="px-4 py-8">
        <div className="max-w-7xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-6">
            {/* Controls Card */}
            <div className="bg-slate-900/80 backdrop-blur-sm rounded-2xl border border-slate-700 p-6">
              <div className="text-xs font-semibold text-cyan-400 uppercase tracking-wider mb-4">
                Step 1 · Choose the baseline controls
              </div>
              <h2 className="text-xl font-bold mb-2">Harden the macOS firewall to a default-deny baseline.</h2>
              <p className="text-sm text-slate-400 mb-6">
                This script targets the built-in macOS Application Firewall and aligns with DISA STIG expectations for enabling the firewall, blocking unsolicited inbound connections, and enabling stealth and logging.
              </p>

              <div className="space-y-3 mb-6">
                {controls.map(control => (
                  <div
                    key={control.key}
                    onClick={() => handleControlToggle(control.key)}
                    className={`p-4 rounded-xl border-2 transition-all cursor-pointer ${
                      selectedControls[control.key]
                        ? 'border-cyan-500 bg-cyan-500/10'
                        : 'border-slate-700 hover:border-slate-600 bg-slate-800/30'
                    }`}
                  >
                    <div className="flex items-start space-x-3">
                      <input
                        type="checkbox"
                        checked={selectedControls[control.key] || false}
                        onChange={() => {}}
                        className="mt-1 w-4 h-4 rounded accent-cyan-500"
                      />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center flex-wrap gap-2 mb-1">
                          <h3 className="font-semibold text-sm">{control.title}</h3>
                          {control.badge && (
                            <span className={`text-xs px-2 py-0.5 rounded-full border ${getBadgeColor(control.badgeColor)}`}>
                              {control.badge}
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-slate-400 leading-relaxed">{control.description}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              <div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-4 mb-4">
                <p className="text-xs text-slate-300 leading-relaxed">
                  <strong className="text-slate-100">Note:</strong> The script generator will include or skip each firewall action according to your checkbox selections. Backups and rollback are strongly recommended, but you can turn them off in the generated script if you really need to.
                </p>
              </div>

              <div className="flex flex-wrap gap-3">
                <button
                  onClick={() => generateScript()}
                  className="flex items-center space-x-2 px-6 py-3 rounded-lg bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 transition-all font-semibold shadow-lg shadow-cyan-500/20"
                >
                  <Settings className="w-4 h-4" />
                  <span>Generate Bash script</span>
                </button>
                <button
                  onClick={clearAll}
                  className="flex items-center space-x-2 px-6 py-3 rounded-lg border border-slate-700 hover:border-red-500 transition-all hover:bg-red-500/10 text-red-400 font-semibold"
                >
                  <Trash2 className="w-4 h-4" />
                  <span>Clear all</span>
                </button>
              </div>
            </div>

            {/* Output Card */}
            <div className="bg-slate-900/80 backdrop-blur-sm rounded-2xl border border-slate-700 p-6">
              <div className="text-xs font-semibold text-cyan-400 uppercase tracking-wider mb-4">
                Step 2 · Copy, test, then run
              </div>
              <h2 className="text-xl font-bold mb-2">Generated macOS firewall baseline script</h2>
              <p className="text-sm text-slate-400 mb-4">
                Review every line, test on a non-critical macOS system, then run from a terminal with root privileges.
              </p>

              <div className="relative mb-4">
                <textarea
                  value={scriptOutput}
                  readOnly
                  className="w-full h-96 p-4 rounded-xl bg-slate-950 border border-slate-700 text-xs font-mono text-slate-300 resize-none focus:outline-none focus:ring-2 focus:ring-cyan-500"
                  placeholder="Script will appear here..."
                />
              </div>

              <div className="flex flex-wrap gap-3 mb-4">
                <button
                  onClick={copyToClipboard}
                  disabled={!scriptOutput}
                  className="flex items-center space-x-2 px-4 py-2 rounded-lg font-semibold border border-slate-700 hover:border-cyan-500 transition-all hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Copy className="w-4 h-4" />
                  <span>Copy to clipboard</span>
                </button>
                
                <select
                  value={downloadFormat}
                  onChange={(e) => setDownloadFormat(e.target.value)}
                  className="px-4 py-2 rounded-lg bg-slate-800 border border-slate-700 hover:border-slate-600 transition-all focus:outline-none focus:ring-2 focus:ring-cyan-500 text-sm"
                >
                  <option value="sh">Download as .sh</option>
                  <option value="txt">Download as .txt</option>
                </select>

                <button
                  onClick={downloadScript}
                  disabled={!scriptOutput}
                  className="flex items-center space-x-2 px-4 py-2 rounded-lg font-semibold border border-slate-700 hover:border-cyan-500 transition-all hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Download className="w-4 h-4" />
                  <span>Download file</span>
                </button>
              </div>

              <div className="space-y-3 text-xs text-slate-400">
                <p>
                  <strong className="text-slate-300">How to use:</strong> Save the script as{' '}
                  <code className="text-cyan-400">macos_firewall_stig.sh</code>, make it executable with{' '}
                  <code className="text-cyan-400">chmod +x macos_firewall_stig.sh</code>, then run{' '}
                  <code className="text-cyan-400">sudo ./macos_firewall_stig.sh apply</code> to back up your current settings and apply the hardened baseline. To restore the most recent backup (if present), run{' '}
                  <code className="text-cyan-400">sudo ./macos_firewall_stig.sh rollback</code>.
                </p>
                <p>
                  <strong className="text-slate-300">Rollback scope:</strong> Rollback restores the last firewall plist backup created by this script under{' '}
                  <code className="text-cyan-400">/usr/local/macos-firewall-backups</code>. It does not modify other security tools, MDM profiles, or network policies that may also affect firewall behavior.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Info Section */}
      <section className="px-4 pb-20">
        <div className="max-w-7xl mx-auto bg-slate-900/80 backdrop-blur-sm rounded-2xl border border-slate-700 p-8">
          <div className="text-xs font-semibold text-cyan-400 uppercase tracking-wider mb-4">
            How to use this assistant safely
          </div>
          
          <div className="grid md:grid-cols-2 gap-8 mb-8">
            <div>
              <h3 className="text-lg font-bold mb-3">Before you run the script</h3>
              <ul className="space-y-2 text-sm text-slate-400">
                <li>• Use this only on macOS systems that you own or are authorized to manage.</li>
                <li>• Ensure you have a recent backup or snapshot of at least one test machine.</li>
                <li>• Read through the comments and commands inside the script before running it.</li>
                <li>• Adjust paths or behavior only if you fully understand the impact.</li>
                <li>• Test on a non-critical device first, then move to systems that matter.</li>
              </ul>
            </div>
            <div>
              <h3 className="text-lg font-bold mb-3">What the script changes</h3>
              <ul className="space-y-2 text-sm text-slate-400">
                <li>• Optionally exports the current macOS firewall plist to a timestamped backup file.</li>
                <li>• Enables the Application Firewall and can enforce a default-deny inbound posture.</li>
                <li>• Can turn on stealth mode and firewall logging to increase visibility.</li>
                <li>• Can disable automatic allow rules for signed and downloaded applications.</li>
                <li>• Provides a basic rollback function if you choose to include backups.</li>
              </ul>
            </div>
          </div>

          {/* Disclaimer */}
          <div className="bg-gradient-to-r from-yellow-500/10 to-orange-500/10 border-2 border-yellow-500/30 rounded-xl p-6">
            <div className="flex items-start space-x-4">
              <AlertTriangle className="w-8 h-8 text-yellow-400 flex-shrink-0" />
              <div>
                <h4 className="text-sm font-bold text-yellow-400 uppercase tracking-wider mb-2">Important Notice</h4>
                <p className="text-sm text-slate-300 leading-relaxed mb-3">
                  This assistant runs entirely in your browser. Your selections and the generated script are not sent to CyberLife Coach, to Apple, or to any third party. The output is a generic starting point and is provided for educational and informational use only. It is not a substitute for professional or command policy guidance, does not guarantee compliance with DISA STIGs or any other standard, and is used at your own risk. Always test in a safe environment, verify every line, and ensure you have reliable backups before making changes. Do not apply these settings to employer, DoD, or school managed devices without explicit approval, and do not bypass existing MDM profiles, configuration profiles, or enterprise change-control processes.
                </p>
                <div className="flex flex-wrap gap-2">
                  <span className="text-xs px-3 py-1 rounded-full bg-red-500/10 text-red-400 border border-red-500/30">No warranty or guarantees</span>
                  <span className="text-xs px-3 py-1 rounded-full bg-green-500/10 text-green-400 border border-green-500/30">Local only, no data leaves this device</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-950 border-t border-slate-800 py-12 px-4">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <Shield className="w-6 h-6 text-cyan-400" />
            <span className="font-bold text-lg">CyberLifeCoach</span>
          </div>
          <div className="text-slate-500 text-sm">
            <p>&copy; 2026 CyberLifeCoach</p>
            <p className="text-slate-600">A Veteran-Owned Business Committed to Your Digital Security</p>
            <p>All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
