import React, { useState } from 'react';
import { Code, ArrowLeft, Copy, Download, RotateCcw } from 'lucide-react';

export default function AnsibleGenerator() {
  const [notification, setNotification] = useState('');
  const [error, setError] = useState('');
  
  // Form state
  const [playName, setPlayName] = useState('');
  const [playHosts, setPlayHosts] = useState('');
  const [playDescription, setPlayDescription] = useState('');
  const [osFamily, setOsFamily] = useState('linux_server');
  const [playBecome, setPlayBecome] = useState(true);
  const [playGatherFacts, setPlayGatherFacts] = useState(true);
  const [explainPlaybook, setExplainPlaybook] = useState(false);
  
  const [enableAdminUser, setEnableAdminUser] = useState(false);
  const [adminUsername, setAdminUsername] = useState('');
  const [adminShell, setAdminShell] = useState('');
  const [adminSudo, setAdminSudo] = useState(true);
  const [sshKeyAuth, setSshKeyAuth] = useState(false);
  const [sshPublicKey, setSshPublicKey] = useState('');
  const [hardenSsh, setHardenSsh] = useState(false);
  
  const [packageList, setPackageList] = useState('');
  const [serviceList, setServiceList] = useState('');
  const [firewallKind, setFirewallKind] = useState('');
  
  const [outputYaml, setOutputYaml] = useState('');

  const showNotification = (msg) => {
    setNotification(msg);
    setTimeout(() => setNotification(''), 3000);
  };

  const getLines = (text) => {
    return text
      .split('\n')
      .map(s => s.trim())
      .filter(s => s.length > 0);
  };

  const yamlEscape = (str) => {
    if (str == null) return '';
    const value = String(str);
    if (/[:#,&*!?|>'"%@`-]/.test(value) || /^\s|\s$/.test(value)) {
      return '"' + value.replace(/"/g, '\\"') + '"';
    }
    return value;
  };

  const generatePlaybook = () => {
    setError('');

    const name = playName.trim() || 'Baseline configuration';
    const hosts = playHosts.trim() || 'all';
    const description = playDescription.trim();
    const packages = getLines(packageList);
    const services = getLines(serviceList);
    const username = adminUsername.trim() || 'ansibleadmin';
    const shell = adminShell.trim() || '/bin/bash';
    const sshKey = sshPublicKey.trim();
    const explain = explainPlaybook;

    if (!hosts) {
      setError('Please provide a hosts pattern such as all or a group name.');
      return;
    }

    if (sshKeyAuth && !sshKey) {
      setError('SSH key based login is selected. Please supply a public key or uncheck the option.');
      return;
    }

    let yaml = '';

    if (explain) {
      yaml += '# Generated by the CyberLife Coach Ansible Playbook Generator\n';
      yaml += '# This play applies a small baseline configuration using common Ansible modules.\n';
      yaml += '# Adjust host groups, packages, and services to match your own lab or environment.\n\n';
    }

    yaml += '---\n';
    if (explain) {
      yaml += '# Play header: which hosts to target and how Ansible should run.\n';
    }
    yaml += '- name: ' + yamlEscape(name) + '\n';
    yaml += '  hosts: ' + yamlEscape(hosts) + '\n';
    yaml += '  become: ' + (playBecome ? 'true' : 'false') + '\n';
    yaml += '  gather_facts: ' + (playGatherFacts ? 'true' : 'false') + '\n';

    if (description) {
      if (explain) {
        yaml += '  # Optional description you can use later inside your own roles or docs.\n';
      }
      yaml += '  vars:\n';
      yaml += '    play_description: ' + yamlEscape(description) + '\n';
    }

    yaml += '  tasks:\n';

    // Admin user
    if (enableAdminUser) {
      if (explain) {
        yaml += '  # User and SSH: create a dedicated admin account rather than logging in as root.\n';
      }
      if (osFamily === 'windows') {
        yaml += '    - name: Ensure admin user exists on Windows\n';
        yaml += '      ansible.windows.win_user:\n';
        yaml += '        name: ' + yamlEscape(username) + '\n';
        yaml += '        state: present\n';
        yaml += '        password_never_expires: true\n';
        if (adminSudo) {
          yaml += '        groups:\n';
          yaml += '          - Administrators\n';
        }
      } else {
        yaml += '    - name: Ensure admin user exists on Linux\n';
        yaml += '      ansible.builtin.user:\n';
        yaml += '        name: ' + yamlEscape(username) + '\n';
        yaml += '        state: present\n';
        yaml += '        shell: ' + yamlEscape(shell) + '\n';
        if (adminSudo) {
          yaml += '        groups: sudo\n';
          yaml += '        append: true\n';
        }

        if (sshKeyAuth && sshKey) {
          yaml += '    - name: Install authorized key for admin user\n';
          yaml += '      ansible.posix.authorized_key:\n';
          yaml += '        user: ' + yamlEscape(username) + '\n';
          yaml += '        state: present\n';
          yaml += '        key: |\n';
          sshKey.split('\n').forEach(line => {
            yaml += '          ' + line + '\n';
          });
        }
      }
    }

    // SSH hardening for Linux
    if (hardenSsh && osFamily !== 'windows') {
      if (explain) {
        yaml += '  # SSH hardening: simple safe defaults, not a full benchmark.\n';
      }
      yaml += '    - name: Harden SSH configuration with simple safe defaults\n';
      yaml += '      ansible.builtin.blockinfile:\n';
      yaml += '        path: /etc/ssh/sshd_config\n';
      yaml += '        marker: "# {mark} managed by Ansible baseline"\n';
      yaml += '        block: |\n';
      yaml += '          Protocol 2\n';
      yaml += '          PermitRootLogin no\n';
      yaml += '          PasswordAuthentication no\n';
      yaml += '          X11Forwarding no\n';
      yaml += '          AllowTcpForwarding no\n';
      yaml += '      notify: restart sshd\n';
    }

    // Packages
    if (packages.length > 0) {
      if (explain) {
        yaml += '  # Packages: keep core tools and services present.\n';
      }
      if (osFamily === 'windows') {
        yaml += '    - name: Ensure packages are present on Windows using Chocolatey\n';
        yaml += '      win_chocolatey:\n';
        yaml += '        name:\n';
        packages.forEach(pkg => {
          yaml += '          - ' + yamlEscape(pkg) + '\n';
        });
        yaml += '        state: present\n';
      } else {
        yaml += '    - name: Ensure packages are present on Linux\n';
        yaml += '      ansible.builtin.package:\n';
        yaml += '        name:\n';
        packages.forEach(pkg => {
          yaml += '          - ' + yamlEscape(pkg) + '\n';
        });
        yaml += '        state: present\n';
      }
    }

    // Firewall helper for Linux
    if (firewallKind && (osFamily === 'linux_server' || osFamily === 'linux_workstation')) {
      if (explain) {
        yaml += '  # Firewall: ensure the chosen firewall component is installed.\n';
        yaml += '  # Replace or extend this section with your own rules and policies.\n';
      }
      if (firewallKind === 'ufw') {
        yaml += '    - name: Ensure ufw is present on Linux\n';
        yaml += '      ansible.builtin.package:\n';
        yaml += '        name: ufw\n';
        yaml += '        state: present\n';
      }
      if (firewallKind === 'firewalld') {
        yaml += '    - name: Ensure firewalld is present on Linux\n';
        yaml += '      ansible.builtin.package:\n';
        yaml += '        name: firewalld\n';
        yaml += '        state: present\n';
      }
    }

    // Services
    if (services.length > 0) {
      if (explain) {
        yaml += '  # Services: keep critical daemons started and enabled at boot.\n';
      }
      if (osFamily === 'windows') {
        services.forEach(svc => {
          yaml += '    - name: Ensure service ' + yamlEscape(svc) + ' is running on Windows\n';
          yaml += '      ansible.windows.win_service:\n';
          yaml += '        name: ' + yamlEscape(svc) + '\n';
          yaml += '        start_mode: auto\n';
          yaml += '        state: running\n';
        });
      } else {
        services.forEach(svc => {
          yaml += '    - name: Ensure service ' + yamlEscape(svc) + ' is running on Linux\n';
          yaml += '      ansible.builtin.service:\n';
          yaml += '        name: ' + yamlEscape(svc) + '\n';
          yaml += '        state: started\n';
          yaml += '        enabled: true\n';
        });
      }
    }

    // Handler for SSH
    if (hardenSsh && osFamily !== 'windows') {
      yaml += '\n';
      if (explain) {
        yaml += '  # Handler: only restarts sshd when the SSH config block changes.\n';
      }
      yaml += '  handlers:\n';
      yaml += '    - name: restart sshd\n';
      yaml += '      ansible.builtin.service:\n';
      yaml += '        name: sshd\n';
      yaml += '        state: restarted\n';
    }

    setOutputYaml(yaml);
    showNotification('Playbook generated successfully');
  };

  const copyPlaybook = () => {
    if (!outputYaml.trim()) {
      setError('Nothing to copy. Generate a playbook first.');
      return;
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(outputYaml).then(
        () => {
          setError('');
          showNotification('Copied to clipboard');
        },
        () => setError('Clipboard copy did not succeed in this browser.')
      );
    } else {
      setError('Clipboard access is not available in this browser.');
    }
  };

  const downloadPlaybook = () => {
    if (!outputYaml.trim()) {
      setError('Nothing to download. Generate a playbook first.');
      return;
    }
    const blob = new Blob([outputYaml], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'playbook.yml';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showNotification('Playbook downloaded');
  };

  const clearForm = () => {
    setPlayName('');
    setPlayHosts('');
    setPlayDescription('');
    setOsFamily('linux_server');
    setPlayBecome(true);
    setPlayGatherFacts(true);
    setExplainPlaybook(false);
    setEnableAdminUser(false);
    setAdminUsername('');
    setAdminShell('');
    setAdminSudo(true);
    setSshKeyAuth(false);
    setSshPublicKey('');
    setHardenSsh(false);
    setPackageList('');
    setServiceList('');
    setFirewallKind('');
    setOutputYaml('');
    setError('');
    showNotification('Form cleared');
  };

  const loadPattern = (pattern) => {
    clearForm();
    if (pattern === 'linux_baseline') {
      setPlayName('Baseline Linux host');
      setPlayHosts('linux_baseline');
      setPlayDescription('Simple baseline for a Linux lab host.');
      setOsFamily('linux_server');
      setEnableAdminUser(true);
      setAdminUsername('ansibleadmin');
      setAdminShell('/bin/bash');
      setAdminSudo(true);
      setHardenSsh(true);
      setFirewallKind('ufw');
      setPackageList('vim\nhtop\nfail2ban');
      setServiceList('sshd');
    }

    if (pattern === 'webserver') {
      setPlayName('Simple web server');
      setPlayHosts('webservers');
      setPlayDescription('Build a very simple HTTP server for lab use.');
      setOsFamily('linux_server');
      setEnableAdminUser(true);
      setAdminUsername('webadmin');
      setAdminShell('/bin/bash');
      setAdminSudo(true);
      setFirewallKind('ufw');
      setPackageList('nginx\nvim');
      setServiceList('nginx');
    }
    showNotification(`Loaded ${pattern === 'linux_baseline' ? 'Linux baseline' : 'web server'} pattern`);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 to-slate-900 text-slate-100">
      {/* Navigation */}
      <nav className="fixed w-full z-50 bg-slate-900/95 backdrop-blur-sm shadow-lg">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-20">
            <a href="/" className="flex items-center space-x-3 group cursor-pointer">
              <img 
                src="/logo.png" 
                alt="CyberLifeCoach" 
                className="h-10 w-auto group-hover:brightness-125 group-hover:scale-110 transition-all duration-300" 
              />
              <span className="text-xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent group-hover:brightness-125 transition-all duration-300">
                CyberLifeCoach
              </span>
            </a>

            <a href="/tools" className="flex items-center space-x-2 text-slate-300 hover:text-cyan-400 transition-colors">
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Tools Hub</span>
            </a>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-32 pb-8 px-4 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-cyan-950/20 to-transparent"></div>
        <div className="absolute inset-0 opacity-20">
          <div className="absolute top-20 left-10 w-72 h-72 bg-cyan-500 rounded-full filter blur-3xl animate-pulse"></div>
        </div>
        
        <div className="relative max-w-7xl mx-auto">
          <div className="flex items-center space-x-4 mb-4">
            <Code className="w-12 h-12 text-cyan-400" />
            <div>
              <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-white via-cyan-200 to-blue-400 bg-clip-text text-transparent">
                Ansible Playbook Generator
              </h1>
              <p className="text-slate-400 mt-2">Build a clean starter playbook for labs, study, or real systems without sending any host details to a server. Choose a few tasks, press generate, then copy the YAML into your own Ansible environment.</p>
            </div>
          </div>
          
          <div className="inline-flex items-center space-x-2 bg-green-900/20 border border-green-500/40 rounded-full px-4 py-2 mt-4">
            <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></span>
            <span className="text-sm text-green-400">Client side only, no accounts</span>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="relative max-w-7xl mx-auto px-4 pb-20">
        <div className="grid lg:grid-cols-2 gap-6">
          {/* Left: Configuration Form */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-8">
            <div className="mb-6">
              <h2 className="text-2xl font-bold text-cyan-400 mb-2">Playbook settings</h2>
              <p className="text-slate-400 text-sm">Describe your hosts and pick a few common tasks. The generator will assemble the YAML for you.</p>
            </div>

            {/* Play Header Section */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider mb-4">Play header</h3>
              
              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Play name</label>
                  <input
                    type="text"
                    value={playName}
                    onChange={(e) => setPlayName(e.target.value)}
                    placeholder="Baseline configuration"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Hosts pattern</label>
                  <input
                    type="text"
                    value={playHosts}
                    onChange={(e) => setPlayHosts(e.target.value)}
                    placeholder="all or webservers or 192.168.10.0/24"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Short description</label>
                  <input
                    type="text"
                    value={playDescription}
                    onChange={(e) => setPlayDescription(e.target.value)}
                    placeholder="Example, baseline Linux server for lab"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Target platform</label>
                  <select
                    value={osFamily}
                    onChange={(e) => setOsFamily(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors h-[88px]"
                    size={3}
                  >
                    <option value="linux_server">Linux server</option>
                    <option value="linux_workstation">Linux workstation</option>
                    <option value="windows">Windows host</option>
                  </select>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <label className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={playBecome}
                    onChange={(e) => setPlayBecome(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                  />
                  <span className="text-slate-300 text-sm">Use privilege escalation</span>
                </label>
                <label className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={playGatherFacts}
                    onChange={(e) => setPlayGatherFacts(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                  />
                  <span className="text-slate-300 text-sm">Gather facts</span>
                </label>
              </div>

              <label className="flex items-center space-x-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={explainPlaybook}
                  onChange={(e) => setExplainPlaybook(e.target.checked)}
                  className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                />
                <span className="text-slate-300 text-sm">Add small inline comments to explain the playbook</span>
              </label>
            </div>

            {/* User Account and SSH Section */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider mb-4">User account and SSH</h3>
              
              <label className="flex items-center space-x-3 cursor-pointer mb-4">
                <input
                  type="checkbox"
                  checked={enableAdminUser}
                  onChange={(e) => setEnableAdminUser(e.target.checked)}
                  className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                />
                <span className="text-slate-300 text-sm">Create a reusable admin user</span>
              </label>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Admin username</label>
                  <input
                    type="text"
                    value={adminUsername}
                    onChange={(e) => setAdminUsername(e.target.value)}
                    placeholder="ansibleadmin"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Login shell (Linux)</label>
                  <input
                    type="text"
                    value={adminShell}
                    onChange={(e) => setAdminShell(e.target.value)}
                    placeholder="/bin/bash"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <label className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={adminSudo}
                    onChange={(e) => setAdminSudo(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                  />
                  <span className="text-slate-300 text-sm">Add user to sudo or administrators group</span>
                </label>
                <label className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={sshKeyAuth}
                    onChange={(e) => setSshKeyAuth(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                  />
                  <span className="text-slate-300 text-sm">Configure SSH key based login</span>
                </label>
              </div>

              {sshKeyAuth && (
                <div className="mb-4">
                  <label className="block text-sm text-slate-400 mb-2">Authorized SSH public key</label>
                  <textarea
                    value={sshPublicKey}
                    onChange={(e) => setSshPublicKey(e.target.value)}
                    placeholder="ssh-ed25519 AAAA... user@example"
                    rows={3}
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors font-mono text-sm"
                  />
                </div>
              )}

              <label className="flex items-center space-x-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={hardenSsh}
                  onChange={(e) => setHardenSsh(e.target.checked)}
                  className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                />
                <span className="text-slate-300 text-sm">Add a simple SSH hardening block for Linux servers</span>
              </label>
            </div>

            {/* Packages and Services Section */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider mb-4">Packages and services</h3>
              
              <div className="mb-4">
                <label className="block text-sm text-slate-400 mb-2">Packages to install</label>
                <textarea
                  value={packageList}
                  onChange={(e) => setPackageList(e.target.value)}
                  placeholder="vim&#10;htop&#10;fail2ban"
                  rows={3}
                  className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors font-mono text-sm"
                />
                <p className="text-slate-500 text-xs mt-2">Enter one package per line. The generator will pick common modules for Linux or Windows.</p>
              </div>

              <div>
                <label className="block text-sm text-slate-400 mb-2">Services to ensure running and enabled</label>
                <textarea
                  value={serviceList}
                  onChange={(e) => setServiceList(e.target.value)}
                  placeholder="sshd&#10;nginx"
                  rows={2}
                  className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors font-mono text-sm"
                />
              </div>
            </div>

            {/* Security Quick Wins Section */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider mb-4">Security quick wins</h3>
              
              <div>
                <label className="block text-sm text-slate-400 mb-2">Firewall helper (Linux)</label>
                <select
                  value={firewallKind}
                  onChange={(e) => setFirewallKind(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors h-[88px]"
                  size={3}
                >
                  <option value="">None</option>
                  <option value="ufw">UFW (Ubuntu style)</option>
                  <option value="firewalld">firewalld (RHEL style)</option>
                </select>
                <p className="text-slate-500 text-xs mt-2">This does not define rules. It only ensures a firewall component is installed and, in some cases, running.</p>
              </div>
            </div>

            {/* Example Patterns */}
            <div className="flex flex-wrap gap-3 mb-6">
              <button
                onClick={() => loadPattern('linux_baseline')}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 text-sm font-semibold transition-all"
              >
                Load example pattern for Linux baseline
              </button>
              <button
                onClick={() => loadPattern('webserver')}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 text-sm font-semibold transition-all"
              >
                Load example pattern for simple web server
              </button>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-3">
              <button
                onClick={generatePlaybook}
                className="flex-1 bg-gradient-to-r from-cyan-500 to-blue-600 px-6 py-3 rounded-lg font-semibold hover:shadow-lg hover:shadow-cyan-500/50 transition-all duration-300 hover:scale-105"
              >
                Generate playbook YAML
              </button>
              <button
                onClick={clearForm}
                className="px-6 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all flex items-center space-x-2"
              >
                <RotateCcw className="w-4 h-4" />
                <span>Clear form</span>
              </button>
            </div>

            {/* Error Message */}
            {error && (
              <div className="mt-4 bg-red-900/20 border border-red-500/40 rounded-lg p-4 text-red-200 text-sm">
                {error}
              </div>
            )}
          </div>

          {/* Right: Output */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-8">
            <div className="mb-6">
              <h2 className="text-2xl font-bold text-cyan-400 mb-2">Generated playbook</h2>
              <p className="text-slate-400 text-sm">Copy this YAML into a file such as playbook.yml then run it with ansible-playbook in your own environment.</p>
            </div>

            <textarea
              value={outputYaml}
              readOnly
              placeholder="Your playbook will appear here after you press Generate."
              className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-4 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors font-mono text-sm min-h-[400px] resize-y"
            />

            <div className="flex gap-3 mt-6 mb-6">
              <button
                onClick={copyPlaybook}
                className="flex items-center space-x-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all"
              >
                <Copy className="w-5 h-5" />
                <span>Copy to clipboard</span>
              </button>
              <button
                onClick={downloadPlaybook}
                className="flex items-center space-x-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all"
              >
                <Download className="w-5 h-5" />
                <span>Download as playbook.yml</span>
              </button>
            </div>

            <p className="text-slate-500 text-sm">
              The generator does not run Ansible. It only builds text based playbooks and leaves all execution inside your own tools and infrastructure.
            </p>
          </div>
        </div>
      </section>

      {/* Legal Disclaimer */}
      <section className="max-w-7xl mx-auto px-4 pb-8">
        <div className="bg-slate-900/50 border border-slate-700 rounded-xl p-6 mb-6">
          <p className="text-sm text-slate-400 leading-relaxed">
            <strong className="text-cyan-400">Important notice:</strong> This Ansible Playbook Generator is an educational and productivity helper. All input and all generation
            happen in your browser. No hostnames, inventories, playbooks, or keys are transmitted to CyberLife Coach
            or to any third party. The output is provided without warranty. Always review and test playbooks in a
            safe environment before you use them on production systems.
          </p>
        </div>

        <p className="text-slate-400 text-sm text-center">
          New to Ansible or want a gentle refresher first?
          <a href="/tools/about-ansible-generator" className="text-cyan-400 hover:text-cyan-300 ml-1">
            Read the companion guide about the Ansible Playbook Generator
          </a>.
        </p>
      </section>

      {/* Footer */}
      <footer className="bg-slate-950 border-t border-slate-800 py-12 px-4 mt-12">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <img 
              src="/logo.png" 
              alt="CyberLifeCoach" 
              className="h-8 w-auto transition-all duration-300 hover:scale-125 hover:brightness-125" 
            />
            <span className="font-bold text-lg transition-all duration-300 hover:text-cyan-400 hover:drop-shadow-[0_0_15px_rgba(34,211,238,0.8)]">
              CyberLifeCoach
            </span>
          </div>
          <div className="text-slate-500 text-sm">
            <p>&copy; {new Date().getFullYear()} CyberLifeCoach</p>
            <p className="text-slate-600">Analysis happens entirely in your browser. No data is sent anywhere.</p>
            <p>All rights reserved.</p>
          </div>
        </div>
      </footer>

      {/* Notification Toast */}
      {notification && (
        <div className="fixed bottom-8 right-8 bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-6 py-3 rounded-lg shadow-lg shadow-cyan-500/50 animate-fade-in z-50">
          {notification}
        </div>
      )}
    </div>
  );
}
