import React, { useState } from 'react';
import { Cloud, ArrowLeft, Copy, Download, RotateCcw } from 'lucide-react';

export default function AWSCloudFormation() {
  const [notification, setNotification] = useState('');
  const [error, setError] = useState('');
  
  // Form state
  const [stackName, setStackName] = useState('');
  const [defaultRegion, setDefaultRegion] = useState('');
  const [templateDescription, setTemplateDescription] = useState('');
  const [environmentTag, setEnvironmentTag] = useState('');
  const [explainTemplate, setExplainTemplate] = useState(false);
  
  // S3 settings
  const [enableS3, setEnableS3] = useState(false);
  const [bucketName, setBucketName] = useState('');
  const [bucketLogsPrefix, setBucketLogsPrefix] = useState('');
  const [bucketVersioning, setBucketVersioning] = useState(true);
  const [bucketBlockPublic, setBucketBlockPublic] = useState(true);
  const [bucketEncryption, setBucketEncryption] = useState(true);
  
  // EC2 settings
  const [enableEC2, setEnableEC2] = useState(false);
  const [ec2LogicalId, setEc2LogicalId] = useState('');
  const [ec2InstanceType, setEc2InstanceType] = useState('');
  const [ec2AmiId, setEc2AmiId] = useState('');
  const [ec2KeyName, setEc2KeyName] = useState('');
  const [ec2SshCidr, setEc2SshCidr] = useState('');
  const [ec2AllowHttp, setEc2AllowHttp] = useState(true);
  const [ec2AllowHttps, setEc2AllowHttps] = useState(false);
  
  // IAM settings
  const [enableIam, setEnableIam] = useState(false);
  const [iamRoleName, setIamRoleName] = useState('');
  const [iamInstanceProfileName, setIamInstanceProfileName] = useState('');
  const [iamSsmManaged, setIamSsmManaged] = useState(true);
  const [iamReadonly, setIamReadonly] = useState(false);
  
  const [addOutputs, setAddOutputs] = useState(true);
  const [outputTemplate, setOutputTemplate] = useState('');

  const showNotification = (msg) => {
    setNotification(msg);
    setTimeout(() => setNotification(''), 3000);
  };

  const yamlEscape = (str) => {
    if (str == null) return '';
    const value = String(str);
    if (/[:#\-\[\]\{\},&*!?|>'"%@`]/.test(value) || /^\s|\s$/.test(value)) {
      return '"' + value.replace(/"/g, '\\"') + '"';
    }
    return value;
  };

  const generateTemplate = () => {
    setError('');

    const stack = stackName.trim() || 'baseline-stack';
    const region = defaultRegion.trim();
    const description = templateDescription.trim() || 'Baseline starter template generated by CyberLife Coach';
    const envTag = environmentTag.trim() || 'dev';
    const explain = explainTemplate;

    const bucket = bucketName.trim();
    const logsPrefix = bucketLogsPrefix.trim();
    
    const logicalId = ec2LogicalId.trim() || 'WebServerInstance';
    const instanceType = ec2InstanceType.trim() || 't3.micro';
    const amiId = ec2AmiId.trim();
    const keyName = ec2KeyName.trim();
    const sshCidr = ec2SshCidr.trim() || '0.0.0.0/0';
    
    const roleName = iamRoleName.trim() || 'EC2BaselineRole';
    const profileName = iamInstanceProfileName.trim() || 'EC2BaselineInstanceProfile';

    if (!enableS3 && !enableEC2 && !enableIam) {
      setError('Select at least one core resource to generate a template.');
      return;
    }

    if (enableS3 && !bucket) {
      setError('S3 bucket is enabled. Please supply a bucket name or uncheck the S3 option.');
      return;
    }

    if (enableEC2) {
      if (!amiId) {
        setError('EC2 instance is enabled. Please supply an AMI ID.');
        return;
      }
      if (!keyName) {
        setError('EC2 instance is enabled. Please supply a key pair name.');
        return;
      }
    }

    if (enableIam && !iamSsmManaged && !iamReadonly) {
      setError('IAM role is enabled. Select at least one managed policy to attach.');
      return;
    }

    let yaml = '';

    if (explain) {
      yaml += '# Generated by the CyberLife Coach AWS CloudFormation Template Generator\n';
      yaml += '# Use this as a starting point for labs and study, then refine it for your own environments.\n\n';
    }

    yaml += "AWSTemplateFormatVersion: '2010-09-09'\n";
    yaml += 'Description: ' + yamlEscape(description) + '\n\n';

    yaml += 'Metadata:\n';
    yaml += '  CyberLifeCoach:\n';
    yaml += '    TemplateOwner: ' + yamlEscape(stack) + '\n';
    if (region) {
      yaml += '    IntendedRegion: ' + yamlEscape(region) + '\n';
    }
    yaml += '\n';

    if (explain) {
      yaml += '# Resources section defines what CloudFormation will create for you.\n';
    }
    yaml += 'Resources:\n';

    let anyResource = false;
    let outputs = '';

    // S3 bucket
    if (enableS3) {
      anyResource = true;
      if (explain) {
        yaml += '  # Private S3 bucket with versioning, encryption, and block public access.\n';
      }
      yaml += '  S3BaselineBucket:\n';
      yaml += '    Type: AWS::S3::Bucket\n';
      yaml += '    Properties:\n';
      yaml += '      BucketName: ' + yamlEscape(bucket) + '\n';
      yaml += '      Tags:\n';
      yaml += '        - Key: Environment\n';
      yaml += '          Value: ' + yamlEscape(envTag) + '\n';
      yaml += '        - Key: Owner\n';
      yaml += '          Value: ' + yamlEscape(stack) + '\n';

      if (bucketVersioning) {
        yaml += '      VersioningConfiguration:\n';
        yaml += '        Status: Enabled\n';
      }

      if (bucketEncryption) {
        yaml += '      BucketEncryption:\n';
        yaml += '        ServerSideEncryptionConfiguration:\n';
        yaml += '          - ServerSideEncryptionByDefault:\n';
        yaml += '              SSEAlgorithm: AES256\n';
      }

      if (logsPrefix) {
        yaml += '      LoggingConfiguration:\n';
        yaml += '        DestinationBucketName: ' + yamlEscape(bucket) + '\n';
        yaml += '        LogFilePrefix: ' + yamlEscape(logsPrefix) + '\n';
      }

      if (bucketBlockPublic) {
        yaml += '      PublicAccessBlockConfiguration:\n';
        yaml += '        BlockPublicAcls: true\n';
        yaml += '        BlockPublicPolicy: true\n';
        yaml += '        IgnorePublicAcls: true\n';
        yaml += '        RestrictPublicBuckets: true\n';
      }

      yaml += '\n';

      if (addOutputs) {
        if (explain) {
          outputs += '  # Expose bucket name as an output for quick reference.\n';
        }
        outputs += '  BucketName:\n';
        outputs += '    Description: Baseline private S3 bucket name\n';
        outputs += '    Value: !Ref S3BaselineBucket\n';
        outputs += '    Export:\n';
        outputs += '      Name: !Sub "${AWS::StackName}-BucketName"\n';
      }
    }

    // IAM role and instance profile
    if (enableIam) {
      anyResource = true;
      if (explain) {
        yaml += '  # IAM role for EC2 instances with managed policies for SSM and optional read only access.\n';
      }
      yaml += '  EC2BaselineRole:\n';
      yaml += '    Type: AWS::IAM::Role\n';
      yaml += '    Properties:\n';
      yaml += '      RoleName: ' + yamlEscape(roleName) + '\n';
      yaml += '      AssumeRolePolicyDocument:\n';
      yaml += "        Version: '2012-10-17'\n";
      yaml += '        Statement:\n';
      yaml += '          - Effect: Allow\n';
      yaml += '            Principal:\n';
      yaml += '              Service: ec2.amazonaws.com\n';
      yaml += '            Action: sts:AssumeRole\n';
      yaml += '      ManagedPolicyArns:\n';
      if (iamSsmManaged) {
        yaml += '        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore\n';
      }
      if (iamReadonly) {
        yaml += '        - arn:aws:iam::aws:policy/ReadOnlyAccess\n';
      }
      yaml += '      Tags:\n';
      yaml += '        - Key: Environment\n';
      yaml += '          Value: ' + yamlEscape(envTag) + '\n';
      yaml += '        - Key: Owner\n';
      yaml += '          Value: ' + yamlEscape(stack) + '\n\n';

      if (explain) {
        yaml += '  # Instance profile to attach the role to EC2 instances.\n';
      }
      yaml += '  EC2BaselineInstanceProfile:\n';
      yaml += '    Type: AWS::IAM::InstanceProfile\n';
      yaml += '    Properties:\n';
      yaml += '      InstanceProfileName: ' + yamlEscape(profileName) + '\n';
      yaml += '      Roles:\n';
      yaml += '        - !Ref EC2BaselineRole\n\n';

      if (addOutputs) {
        if (outputs.length > 0) outputs += '\n';
        if (explain) {
          outputs += '  # Expose instance profile name.\n';
        }
        outputs += '  InstanceProfileName:\n';
        outputs += '    Description: EC2 instance profile name\n';
        outputs += '    Value: !Ref EC2BaselineInstanceProfile\n';
      }
    }

    // EC2 and security group
    if (enableEC2) {
      anyResource = true;
      if (explain) {
        yaml += '  # Security group for a small lab web server.\n';
      }
      yaml += '  WebServerSecurityGroup:\n';
      yaml += '    Type: AWS::EC2::SecurityGroup\n';
      yaml += '    Properties:\n';
      yaml += '      GroupDescription: Baseline security group for a small web server\n';
      yaml += '      VpcId: !Ref AWS::NoValue\n';
      yaml += '      SecurityGroupIngress:\n';
      yaml += '        - IpProtocol: tcp\n';
      yaml += '          FromPort: 22\n';
      yaml += '          ToPort: 22\n';
      yaml += '          CidrIp: ' + yamlEscape(sshCidr) + '\n';

      if (ec2AllowHttp) {
        yaml += '        - IpProtocol: tcp\n';
        yaml += '          FromPort: 80\n';
        yaml += '          ToPort: 80\n';
        yaml += '          CidrIp: 0.0.0.0/0\n';
      }
      if (ec2AllowHttps) {
        yaml += '        - IpProtocol: tcp\n';
        yaml += '          FromPort: 443\n';
        yaml += '          ToPort: 443\n';
        yaml += '          CidrIp: 0.0.0.0/0\n';
      }

      yaml += '      Tags:\n';
      yaml += '        - Key: Name\n';
      yaml += '          Value: WebServerSecurityGroup\n';
      yaml += '        - Key: Environment\n';
      yaml += '          Value: ' + yamlEscape(envTag) + '\n\n';

      if (explain) {
        yaml += '  # EC2 instance for lab use, attach key pair and optional IAM instance profile.\n';
      }
      const ec2IdSafe = logicalId.match(/^[A-Za-z_][A-Za-z0-9_]*$/) ? logicalId : 'WebServerInstance';
      yaml += '  ' + ec2IdSafe + ':\n';
      yaml += '    Type: AWS::EC2::Instance\n';
      yaml += '    Properties:\n';
      yaml += '      InstanceType: ' + yamlEscape(instanceType) + '\n';
      yaml += '      ImageId: ' + yamlEscape(amiId) + '\n';
      yaml += '      KeyName: ' + yamlEscape(keyName) + '\n';
      yaml += '      SecurityGroupIds:\n';
      yaml += '        - !Ref WebServerSecurityGroup\n';

      if (enableIam) {
        yaml += '      IamInstanceProfile: !Ref EC2BaselineInstanceProfile\n';
      }

      yaml += '      Tags:\n';
      yaml += '        - Key: Name\n';
      yaml += '          Value: ' + yamlEscape(ec2IdSafe) + '\n';
      yaml += '        - Key: Environment\n';
      yaml += '          Value: ' + yamlEscape(envTag) + '\n\n';

      if (addOutputs) {
        if (outputs.length > 0) outputs += '\n';
        if (explain) {
          outputs += '  # Expose instance ID as a simple output.\n';
        }
        outputs += '  WebInstanceId:\n';
        outputs += '    Description: EC2 instance ID for the lab web server\n';
        outputs += '    Value: !Ref ' + ec2IdSafe + '\n';
      }
    }

    if (!anyResource) {
      setError('No resources were added. Select at least one of S3, EC2, or IAM.');
      return;
    }

    if (addOutputs && outputs.trim().length > 0) {
      yaml += 'Outputs:\n';
      yaml += outputs;
      yaml += '\n';
    }

    setOutputTemplate(yaml);
    showNotification('CloudFormation template generated successfully');
  };

  const copyTemplate = () => {
    if (!outputTemplate.trim()) {
      setError('Nothing to copy. Generate a template first.');
      return;
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(outputTemplate).then(
        () => {
          setError('');
          showNotification('Copied to clipboard');
        },
        () => setError('Clipboard copy did not succeed in this browser.')
      );
    } else {
      setError('Clipboard access is not available in this browser.');
    }
  };

  const downloadTemplate = () => {
    if (!outputTemplate.trim()) {
      setError('Nothing to download. Generate a template first.');
      return;
    }
    const blob = new Blob([outputTemplate], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'template.yaml';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showNotification('Template downloaded');
  };

  const clearForm = () => {
    setStackName('');
    setDefaultRegion('');
    setTemplateDescription('');
    setEnvironmentTag('');
    setExplainTemplate(false);
    setEnableS3(false);
    setBucketName('');
    setBucketLogsPrefix('');
    setBucketVersioning(true);
    setBucketBlockPublic(true);
    setBucketEncryption(true);
    setEnableEC2(false);
    setEc2LogicalId('');
    setEc2InstanceType('');
    setEc2AmiId('');
    setEc2KeyName('');
    setEc2SshCidr('');
    setEc2AllowHttp(true);
    setEc2AllowHttps(false);
    setEnableIam(false);
    setIamRoleName('');
    setIamInstanceProfileName('');
    setIamSsmManaged(true);
    setIamReadonly(false);
    setAddOutputs(true);
    setOutputTemplate('');
    setError('');
    showNotification('Form cleared');
  };

  const loadPattern = (pattern) => {
    clearForm();

    if (pattern === 's3_private_bucket') {
      setStackName('s3-private-bucket-stack');
      setTemplateDescription('Private S3 bucket with versioning, encryption, and block public access.');
      setEnvironmentTag('dev');
      setEnableS3(true);
      setBucketName('my-private-bucket-example');
      setBucketLogsPrefix('logs/');
      setBucketVersioning(true);
      setBucketBlockPublic(true);
      setBucketEncryption(true);
      setAddOutputs(true);
    }

    if (pattern === 'ec2_web_lab') {
      setStackName('ec2-web-lab-stack');
      setTemplateDescription('Small EC2 web server for lab use with basic security group.');
      setEnvironmentTag('lab');
      setEnableEC2(true);
      setEc2LogicalId('WebServerInstance');
      setEc2InstanceType('t3.micro');
      setEc2AmiId('ami-0123456789abcdef0');
      setEc2KeyName('my-keypair-name');
      setEc2SshCidr('0.0.0.0/0');
      setEc2AllowHttp(true);
      setEc2AllowHttps(false);
      setEnableIam(true);
      setIamRoleName('EC2BaselineRole');
      setIamInstanceProfileName('EC2BaselineInstanceProfile');
      setIamSsmManaged(true);
      setIamReadonly(false);
      setAddOutputs(true);
    }
    showNotification(`Loaded ${pattern === 's3_private_bucket' ? 'S3 private bucket' : 'EC2 web lab'} pattern`);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-950 to-slate-900 text-slate-100">
      {/* Navigation */}
      <nav className="fixed w-full z-50 bg-slate-900/95 backdrop-blur-sm shadow-lg">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-20">
            <a href="/" className="flex items-center space-x-3 group cursor-pointer">
              <img 
                src="/logo.png" 
                alt="CyberLifeCoach" 
                className="h-10 w-auto group-hover:brightness-125 group-hover:scale-110 transition-all duration-300" 
              />
              <span className="text-xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent group-hover:brightness-125 transition-all duration-300">
                CyberLifeCoach
              </span>
            </a>

            <a href="/tools" className="flex items-center space-x-2 text-slate-300 hover:text-cyan-400 transition-colors">
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Tools Hub</span>
            </a>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-32 pb-8 px-4 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-cyan-950/20 to-transparent"></div>
        <div className="absolute inset-0 opacity-20">
          <div className="absolute top-20 left-10 w-72 h-72 bg-cyan-500 rounded-full filter blur-3xl animate-pulse"></div>
        </div>
        
        <div className="relative max-w-7xl mx-auto">
          <div className="flex items-center space-x-4 mb-4">
            <Cloud className="w-12 h-12 text-cyan-400" />
            <div>
              <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-white via-cyan-200 to-blue-400 bg-clip-text text-transparent">
                AWS CloudFormation Template Generator
              </h1>
              <p className="text-slate-400 mt-2">Draft a clean starter CloudFormation template for labs, study, or real AWS environments, entirely in your browser. Choose a few common resources, press generate, then copy the YAML into your own CloudFormation workflow.</p>
            </div>
          </div>
          
          <div className="inline-flex items-center space-x-2 bg-green-900/20 border border-green-500/40 rounded-full px-4 py-2 mt-4">
            <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></span>
            <span className="text-sm text-green-400">Client side only, no AWS calls</span>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="relative max-w-7xl mx-auto px-4 pb-20">
        <div className="grid lg:grid-cols-2 gap-6">
          {/* Left: Configuration Form */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-8">
            <div className="mb-6">
              <h2 className="text-2xl font-bold text-cyan-400 mb-2">Template settings</h2>
              <p className="text-slate-400 text-sm">Describe the stack and select resources. The generator assembles a starter CloudFormation template.</p>
            </div>

            {/* Template Header Section */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider mb-4">Template header</h3>
              
              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Stack name</label>
                  <input
                    type="text"
                    value={stackName}
                    onChange={(e) => setStackName(e.target.value)}
                    placeholder="baseline-stack"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Intended AWS Region</label>
                  <input
                    type="text"
                    value={defaultRegion}
                    onChange={(e) => setDefaultRegion(e.target.value)}
                    placeholder="us-east-1, eu-west-1"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Short description</label>
                  <input
                    type="text"
                    value={templateDescription}
                    onChange={(e) => setTemplateDescription(e.target.value)}
                    placeholder="Baseline lab environment for AWS"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Environment tag</label>
                  <input
                    type="text"
                    value={environmentTag}
                    onChange={(e) => setEnvironmentTag(e.target.value)}
                    placeholder="dev, test, or prod"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
              </div>

              <label className="flex items-center space-x-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={explainTemplate}
                  onChange={(e) => setExplainTemplate(e.target.checked)}
                  className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                />
                <span className="text-slate-300 text-sm">Add small inline comments to explain the template</span>
              </label>
            </div>

            {/* Core Resources Section */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider mb-4">Core resources</h3>
              
              {/* S3 Bucket */}
              <label className="flex items-center space-x-3 cursor-pointer mb-4">
                <input
                  type="checkbox"
                  checked={enableS3}
                  onChange={(e) => setEnableS3(e.target.checked)}
                  className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                />
                <span className="text-slate-300 text-sm">Add an S3 bucket with sensible privacy defaults</span>
              </label>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Bucket name</label>
                  <input
                    type="text"
                    value={bucketName}
                    onChange={(e) => setBucketName(e.target.value)}
                    placeholder="my-baseline-bucket"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Log prefix (optional)</label>
                  <input
                    type="text"
                    value={bucketLogsPrefix}
                    onChange={(e) => setBucketLogsPrefix(e.target.value)}
                    placeholder="logs/"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <label className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={bucketVersioning}
                    onChange={(e) => setBucketVersioning(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                  />
                  <span className="text-slate-300 text-sm">Enable versioning</span>
                </label>
                <label className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={bucketBlockPublic}
                    onChange={(e) => setBucketBlockPublic(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                  />
                  <span className="text-slate-300 text-sm">Block all public access</span>
                </label>
              </div>

              <label className="flex items-center space-x-3 cursor-pointer mb-4">
                <input
                  type="checkbox"
                  checked={bucketEncryption}
                  onChange={(e) => setBucketEncryption(e.target.checked)}
                  className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                />
                <span className="text-slate-300 text-sm">Enable server side encryption (SSE-S3)</span>
              </label>

              <hr className="border-slate-700 my-6" />

              {/* EC2 Instance */}
              <label className="flex items-center space-x-3 cursor-pointer mb-4">
                <input
                  type="checkbox"
                  checked={enableEC2}
                  onChange={(e) => setEnableEC2(e.target.checked)}
                  className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                />
                <span className="text-slate-300 text-sm">Add a small EC2 instance and security group</span>
              </label>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-2">EC2 logical ID</label>
                  <input
                    type="text"
                    value={ec2LogicalId}
                    onChange={(e) => setEc2LogicalId(e.target.value)}
                    placeholder="WebServerInstance"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Instance type</label>
                  <input
                    type="text"
                    value={ec2InstanceType}
                    onChange={(e) => setEc2InstanceType(e.target.value)}
                    placeholder="t3.micro"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-2">AMI ID</label>
                  <input
                    type="text"
                    value={ec2AmiId}
                    onChange={(e) => setEc2AmiId(e.target.value)}
                    placeholder="ami-0123456789abcdef0"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Key pair name</label>
                  <input
                    type="text"
                    value={ec2KeyName}
                    onChange={(e) => setEc2KeyName(e.target.value)}
                    placeholder="my-keypair-name"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
              </div>

              <div className="mb-4">
                <label className="block text-sm text-slate-400 mb-2">SSH allowed CIDR</label>
                <input
                  type="text"
                  value={ec2SshCidr}
                  onChange={(e) => setEc2SshCidr(e.target.value)}
                  placeholder="0.0.0.0/0 (for labs only)"
                  className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                />
                <p className="text-slate-500 text-xs mt-2">Use a narrow range such as your office IP for anything beyond lab work.</p>
              </div>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <label className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={ec2AllowHttp}
                    onChange={(e) => setEc2AllowHttp(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                  />
                  <span className="text-slate-300 text-sm">Allow HTTP (port 80) in the security group</span>
                </label>
                <label className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={ec2AllowHttps}
                    onChange={(e) => setEc2AllowHttps(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                  />
                  <span className="text-slate-300 text-sm">Allow HTTPS (port 443) in the security group</span>
                </label>
              </div>

              <hr className="border-slate-700 my-6" />

              {/* IAM Role */}
              <label className="flex items-center space-x-3 cursor-pointer mb-4">
                <input
                  type="checkbox"
                  checked={enableIam}
                  onChange={(e) => setEnableIam(e.target.checked)}
                  className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                />
                <span className="text-slate-300 text-sm">Add a basic IAM role for EC2</span>
              </label>

              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Role name</label>
                  <input
                    type="text"
                    value={iamRoleName}
                    onChange={(e) => setIamRoleName(e.target.value)}
                    placeholder="EC2BaselineRole"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
                <div>
                  <label className="block text-sm text-slate-400 mb-2">Instance profile name</label>
                  <input
                    type="text"
                    value={iamInstanceProfileName}
                    onChange={(e) => setIamInstanceProfileName(e.target.value)}
                    placeholder="EC2BaselineInstanceProfile"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <label className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={iamSsmManaged}
                    onChange={(e) => setIamSsmManaged(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                  />
                  <span className="text-slate-300 text-sm">Attach AmazonSSMManagedInstanceCore</span>
                </label>
                <label className="flex items-center space-x-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={iamReadonly}
                    onChange={(e) => setIamReadonly(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                  />
                  <span className="text-slate-300 text-sm">Attach ReadOnlyAccess</span>
                </label>
              </div>
            </div>

            {/* Outputs Section */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider mb-4">Outputs</h3>
              <label className="flex items-center space-x-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={addOutputs}
                  onChange={(e) => setAddOutputs(e.target.checked)}
                  className="w-5 h-5 rounded border-slate-600 bg-slate-900 text-cyan-500 focus:ring-cyan-500 focus:ring-offset-slate-900"
                />
                <span className="text-slate-300 text-sm">Add simple Outputs for created resources</span>
              </label>
            </div>

            {/* Example Patterns */}
            <div className="flex flex-wrap gap-3 mb-6">
              <button
                onClick={() => loadPattern('s3_private_bucket')}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 text-sm font-semibold transition-all"
              >
                Load pattern for private S3 bucket
              </button>
              <button
                onClick={() => loadPattern('ec2_web_lab')}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 text-sm font-semibold transition-all"
              >
                Load pattern for small EC2 web lab
              </button>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-3">
              <button
                onClick={generateTemplate}
                className="flex-1 bg-gradient-to-r from-cyan-500 to-blue-600 px-6 py-3 rounded-lg font-semibold hover:shadow-lg hover:shadow-cyan-500/50 transition-all duration-300 hover:scale-105"
              >
                Generate CloudFormation YAML
              </button>
              <button
                onClick={clearForm}
                className="px-6 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all flex items-center space-x-2"
              >
                <RotateCcw className="w-4 h-4" />
                <span>Clear form</span>
              </button>
            </div>

            {/* Error Message */}
            {error && (
              <div className="mt-4 bg-red-900/20 border border-red-500/40 rounded-lg p-4 text-red-200 text-sm">
                {error}
              </div>
            )}
          </div>

          {/* Right: Output */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-8">
            <div className="mb-6">
              <h2 className="text-2xl font-bold text-cyan-400 mb-2">Generated template</h2>
              <p className="text-slate-400 text-sm">Copy this YAML into a file such as template.yaml then deploy it with your own AWS tools.</p>
            </div>

            <textarea
              value={outputTemplate}
              readOnly
              placeholder="Your CloudFormation template will appear here after you press Generate."
              className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-4 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors font-mono text-sm min-h-[400px] resize-y"
            />

            <div className="flex gap-3 mt-6 mb-6">
              <button
                onClick={copyTemplate}
                className="flex items-center space-x-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all"
              >
                <Copy className="w-5 h-5" />
                <span>Copy to clipboard</span>
              </button>
              <button
                onClick={downloadTemplate}
                className="flex items-center space-x-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all"
              >
                <Download className="w-5 h-5" />
                <span>Download as template.yaml</span>
              </button>
            </div>

            <p className="text-slate-500 text-sm">
              The generator does not call AWS APIs. It only builds text based templates and leaves all creation and updates inside your own AWS accounts and deployment tools.
            </p>
          </div>
        </div>
      </section>

      {/* Legal Disclaimer */}
      <section className="max-w-7xl mx-auto px-4 pb-8">
        <div className="bg-slate-900/50 border border-slate-700 rounded-xl p-6 mb-6">
          <p className="text-sm text-slate-400 leading-relaxed">
            <strong className="text-cyan-400">Important notice:</strong> This AWS CloudFormation Template Generator is an educational and productivity helper. All input and all generation
            happen in your browser. No AWS credentials, stack data, or resource identifiers are transmitted to CyberLife Coach
            or to any third party. The output is provided without warranty. Always review and test templates in a safe,
            non-production environment before you use them in live AWS accounts.
          </p>
        </div>

        <p className="text-slate-400 text-sm text-center">
          New to CloudFormation or want a gentle refresher first?
          <a href="/tools/about-cloudformation-generator" className="text-cyan-400 hover:text-cyan-300 ml-1">
            Read the companion guide about the AWS CloudFormation Template Generator
          </a>.
        </p>
      </section>

      {/* Footer */}
      <footer className="bg-slate-950 border-t border-slate-800 py-12 px-4 mt-12">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <img 
              src="/logo.png" 
              alt="CyberLifeCoach" 
              className="h-8 w-auto transition-all duration-300 hover:scale-125 hover:brightness-125" 
            />
            <span className="font-bold text-lg transition-all duration-300 hover:text-cyan-400 hover:drop-shadow-[0_0_15px_rgba(34,211,238,0.8)]">
              CyberLifeCoach
            </span>
          </div>
          <div className="text-slate-500 text-sm">
            <p>&copy; {new Date().getFullYear()} CyberLifeCoach</p>
            <p className="text-slate-600">Analysis happens entirely in your browser. No data is sent anywhere.</p>
            <p>All rights reserved.</p>
          </div>
        </div>
      </footer>

      {/* Notification Toast */}
      {notification && (
        <div className="fixed bottom-8 right-8 bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-6 py-3 rounded-lg shadow-lg shadow-cyan-500/50 animate-fade-in z-50">
          {notification}
        </div>
      )}
    </div>
  );
}
