import React, { useState, useEffect } from 'react';
import { Shield, ArrowLeft, Copy, Download, RefreshCw, Eye, EyeOff, Server, Monitor, Code, Save, Upload } from 'lucide-react';

export default function FirewallConfigurator() {
  // State for OS and platform
  const [targetOs, setTargetOs] = useState('linux');
  const [firewallType, setFirewallType] = useState('ufw');
  const [windowsEngine, setWindowsEngine] = useState('powershell');
  const [systemRole, setSystemRole] = useState('desktop');
  
  // Services state
  const [services, setServices] = useState({
    '22': false,
    '80': false,
    '443': false,
    '53-udp': false,
    '3000': false,
    '5000': false,
    'docker': false
  });
  
  // Admin IP state
  const [allowMyIp, setAllowMyIp] = useState(false);
  const [ipMode, setIpMode] = useState('auto');
  const [manualIp, setManualIp] = useState('');
  const [detectedIp, setDetectedIp] = useState('');
  
  // Country blocking state
  const [selectedCountries, setSelectedCountries] = useState([]);
  const [includeIpv6, setIncludeIpv6] = useState(false);
  
  // UI state
  const [output, setOutput] = useState('');
  const [showPreview, setShowPreview] = useState(false);
  const [notification, setNotification] = useState('');
  
  // Notification cleanup effect
  useEffect(() => {
    if (notification) {
      const timer = setTimeout(() => setNotification(''), 3000);
      return () => clearTimeout(timer);
    }
  }, [notification]);

  const showNotification = (msg) => {
    setNotification(msg);
  };

  const countries = [
    { code: 'cn', name: 'China (CN)' },
    { code: 'ru', name: 'Russia (RU)' },
    { code: 'ir', name: 'Iran (IR)' },
    { code: 'kp', name: 'North Korea (KP)' },
    { code: 'sy', name: 'Syria (SY)' },
    { code: 'pk', name: 'Pakistan (PK)' },
    { code: 'in', name: 'India (IN)' },
    { code: 'br', name: 'Brazil (BR)' },
    { code: 'us', name: 'United States (US)' },
    { code: 'de', name: 'Germany (DE)' }
  ];

  // Effect to detect IP when conditions change
  useEffect(() => {
    let isMounted = true;
    
    const fetchIP = async () => {
      if (allowMyIp && ipMode === 'auto') {
        try {
          const response = await fetch('https://api.ipify.org?format=json', {
            cache: 'no-store',
            mode: 'cors'
          });
          const data = await response.json();
          if (isMounted) {
            setDetectedIp(data.ip);
          }
        } catch (error) {
          console.error('Failed to detect public IP:', error);
          if (isMounted) {
            setDetectedIp('');
          }
        }
      }
    };
    
    fetchIP();
    
    return () => {
      isMounted = false;
    };
  }, [allowMyIp, ipMode]);

  const detectSelectedServices = () => {
    return Object.entries(services)
      .filter(([, checked]) => checked)
      .map(([service]) => service);
  };

  const applyRoleDefaults = (selectedServices) => {
    const servicesArray = [...selectedServices];
    if (systemRole === 'webserver' || systemRole === 'developer') {
      if (!servicesArray.includes('80')) servicesArray.push('80');
      if (!servicesArray.includes('443')) servicesArray.push('443');
    }
    return servicesArray;
  };

  const resolveAdminIp = () => {
    if (!allowMyIp) return null;
    return ipMode === 'manual' ? (manualIp || 'YOUR_IP') : (detectedIp || 'YOUR_IP');
  };

  const escapeBash = (s) => {
    return s == null ? '' : String(s);
  };

  // Generator functions
  const generateUfw = () => {
    const selectedServices = detectSelectedServices();
    const servicesArray = applyRoleDefaults(selectedServices);
    const adminIp = resolveAdminIp();
    
    let script = '#!/bin/bash\nset -e\n';
    script += '# UFW rules generated by Firewall Rule Generator v4.1.1\n';
    script += 'echo "This script will configure UFW. Review before running."\n\n';
    script += 'sudo apt update && sudo apt install ufw -y\n';
    script += 'sudo ufw --force reset\n';
    script += 'sudo ufw default deny incoming\nsudo ufw default allow outgoing\n\n';
    
    if (adminIp) {
      script += `sudo ufw allow from ${escapeBash(adminIp)} to any port 22 proto tcp\n`;
    }
    
    for (const service of servicesArray) {
      if (service === '53-udp') {
        script += 'sudo ufw allow 53/udp\n';
      } else if (service === 'docker') {
        script += '# Docker: open per container\n';
      } else {
        script += `sudo ufw allow ${escapeBash(service)}/tcp\n`;
      }
    }
    
    script += '\n# UFW lacks native ipset country blocking. Use iptables/nftables for that.\n';
    script += 'sudo ufw enable\nsudo ufw status verbose\n';
    
    return script;
  };

  const generateIptables = () => {
    const selectedServices = detectSelectedServices();
    const servicesArray = applyRoleDefaults(selectedServices);
    const adminIp = resolveAdminIp();
    
    let script = '#!/bin/bash\nset -e\n';
    script += '# iptables + ipset rules generated by Firewall Rule Generator v4.1.1\n';
    script += 'echo "Review this script before running. Ensure console access in case of lockout."\n\n';
    script += 'sudo apt update\nsudo apt install -y iptables ipset iptables-persistent curl\n\n';
    script += 'sudo iptables -F\nsudo iptables -X\nsudo iptables -t nat -F\nsudo iptables -t mangle -F\n';
    script += 'sudo iptables -P INPUT DROP\nsudo iptables -P FORWARD DROP\nsudo iptables -P OUTPUT ACCEPT\n\n';
    script += 'sudo iptables -A INPUT -i lo -j ACCEPT\n';
    script += 'sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT\n';
    
    if (adminIp) {
      script += `sudo iptables -A INPUT -p tcp -s ${escapeBash(adminIp)} --dport 22 -m conntrack --ctstate NEW -j ACCEPT\n`;
    }
    
    for (const service of servicesArray) {
      if (service === '53-udp') {
        script += 'sudo iptables -A INPUT -p udp --dport 53 -j ACCEPT\n';
      } else if (service === 'docker') {
        script += '# Docker: manage container nets separately\n';
      } else {
        script += `sudo iptables -A INPUT -p tcp --dport ${escapeBash(service)} -m conntrack --ctstate NEW -j ACCEPT\n`;
      }
    }
    
    script += '\nsudo iptables -A INPUT -m conntrack --ctstate INVALID -j DROP\nsudo iptables -A INPUT -f -j DROP\n\n';
    
    // Country blocking
    if (selectedCountries.length > 0) {
      script += 'sudo mkdir -p /tmp/fw-country && cd /tmp/fw-country\n';
      script += 'echo "Downloading country CIDR lists and creating ipsets..."\n';
      
      for (const cc of selectedCountries) {
        script += `sudo ipset create cc_${cc}_v4 hash:net family inet -exist\n`;
        script += `curl -fsSL https://www.ipdeny.com/ipblocks/data/countries/${cc}.zone -o ${cc}_v4.zone || true\n`;
        script += `if [ -s ${cc}_v4.zone ]; then for ip in $(cat ${cc}_v4.zone); do sudo ipset add cc_${cc}_v4 $ip -exist; done; fi\n`;
        
        if (includeIpv6) {
          script += `sudo ipset create cc_${cc}_v6 hash:net family inet6 -exist\n`;
          script += `curl -fsSL https://www.ipdeny.com/ipblocks/data/ipv6/${cc}.zone -o ${cc}_v6.zone || true\n`;
          script += `if [ -s ${cc}_v6.zone ]; then for ip in $(cat ${cc}_v6.zone); do sudo ipset add cc_${cc}_v6 $ip -exist; done; fi\n`;
        }
        
        if (adminIp) {
          script += `sudo ipset del cc_${cc}_v4 ${escapeBash(adminIp)} 2>/dev/null || true\n`;
          if (includeIpv6) script += `sudo ipset del cc_${cc}_v6 ${escapeBash(adminIp)} 2>/dev/null || true\n`;
        }
        
        script += `sudo iptables -I INPUT -m set --match-set cc_${cc}_v4 src -j DROP || true\n`;
        if (includeIpv6) script += `sudo ip6tables -I INPUT -m set --match-set cc_${cc}_v6 src -j DROP || true\n`;
      }
      
      script += '\nsudo ipset save > /etc/ipset.conf\n';
    }
    
    script += '\nsudo iptables -N FW-LOGDROP || true\n';
    script += 'sudo iptables -A FW-LOGDROP -m limit --limit 2/min --limit-burst 5 -j LOG --log-prefix "iptables-drop: " --log-level 4 || true\n';
    script += 'sudo iptables -A FW-LOGDROP -j DROP || true\n';
    script += 'sudo iptables -A INPUT -j FW-LOGDROP\n\n';
    script += 'sudo netfilter-persistent save || sudo iptables-save > /etc/iptables/rules.v4\n';
    
    return script;
  };

  const generateNftables = () => {
    const selectedServices = detectSelectedServices();
    const servicesArray = applyRoleDefaults(selectedServices);
    const adminIp = resolveAdminIp();
    
    let script = '#!/bin/bash\nset -e\n';
    script += '# nftables rules generated by Firewall Rule Generator v4.1.1\n';
    script += 'sudo apt update\nsudo apt install -y nftables curl\n\n';
    script += 'sudo nft flush ruleset || true\n';
    script += 'sudo nft add table inet filter || true\n';
    script += 'sudo nft "add chain inet filter input { type filter hook input priority 0; policy drop; }" || true\n';
    script += 'sudo nft "add chain inet filter forward { type filter hook forward priority 0; policy drop; }" || true\n';
    script += 'sudo nft "add chain inet filter output { type filter hook output priority 0; policy accept; }" || true\n\n';
    script += 'sudo nft add rule inet filter input iifname lo accept || true\n';
    script += 'sudo nft add rule inet filter input ct state established,related accept || true\n';
    
    if (adminIp) {
      script += `sudo nft add rule inet filter input ip saddr ${escapeBash(adminIp)} tcp dport 22 ct state new accept || true\n`;
    }
    
    for (const service of servicesArray) {
      if (service === '53-udp') {
        script += 'sudo nft add rule inet filter input udp dport 53 accept || true\n';
      } else if (service === 'docker') {
        script += '# Docker: prefer container nets\n';
      } else {
        script += `sudo nft add rule inet filter input tcp dport ${escapeBash(service)} ct state new accept || true\n`;
      }
    }
    
    script += '\nsudo nft add rule inet filter input ct state invalid counter drop || true\n\n';
    
    // Country blocking
    if (selectedCountries.length > 0) {
      for (const cc of selectedCountries) {
        script += `sudo nft add set inet filter cc_${cc}_v4 { type ipv4_addr; flags interval; } || true\n`;
        script += `curl -fsSL https://www.ipdeny.com/ipblocks/data/countries/${cc}.zone -o /tmp/${cc}_v4.zone || true\n`;
        script += `if [ -s /tmp/${cc}_v4.zone ]; then while read -r cid; do sudo nft add element inet filter cc_${cc}_v4 { $cid } 2>/dev/null || true; done < /tmp/${cc}_v4.zone; fi\n`;
        
        if (includeIpv6) {
          script += `sudo nft add set inet filter cc_${cc}_v6 { type ipv6_addr; flags interval; } || true\n`;
          script += `curl -fsSL https://www.ipdeny.com/ipblocks/data/ipv6/${cc}.zone -o /tmp/${cc}_v6.zone || true\n`;
          script += `if [ -s /tmp/${cc}_v6.zone ]; then while read -r cid; do sudo nft add element inet filter cc_${cc}_v6 { $cid } 2>/dev/null || true; done < /tmp/${cc}_v6.zone; fi\n`;
        }
        
        if (adminIp) script += `sudo nft add rule inet filter input ip saddr ${escapeBash(adminIp)} accept || true\n`;
        script += `sudo nft add rule inet filter input ip saddr @cc_${cc}_v4 counter drop || true\n`;
        if (includeIpv6) script += `sudo nft add rule inet filter input ip6 saddr @cc_${cc}_v6 counter drop || true\n`;
      }
    }
    
    script += '\nsudo nft list ruleset > /etc/nftables.conf\nsudo systemctl enable --now nftables\n';
    
    return script;
  };

  const generatePfctl = () => {
    const selectedServices = detectSelectedServices();
    const servicesArray = applyRoleDefaults(selectedServices);
    const adminIp = resolveAdminIp();
    
    let script = '#!/bin/bash\nset -e\n';
    script += '# macOS Packet Filter rules generated by Firewall Rule Generator v4.1.1\n';
    script += 'echo "This script prepares an anchor based pf configuration. Review before running."\n\n';
    script += 'sudo cp /etc/pf.conf /etc/pf.conf.backup-$(date +%F) || true\n\n';
    script += 'ANCHOR="/etc/pf.anchors/com.cyberlifecoach"\nTMP_ANCHOR="$(mktemp /tmp/com.cyberlifecoach.XXXXXX)"\n';
    script += 'cat > "$TMP_ANCHOR" <<\'EOF_PF\'\nset block-policy drop\nset skip on lo0\n\n';
    
    if (adminIp) {
      script += `# Allow admin IP\npass in proto tcp from ${adminIp} to any port 22 keep state\n\n`;
    }
    
    for (const service of servicesArray) {
      if (service === '53-udp') {
        script += 'pass in proto udp from any to any port 53 keep state\n';
      } else if (/^\d+$/.test(service)) {
        script += `pass in proto tcp from any to any port ${service} keep state\n`;
      } else if (service === 'docker') {
        script += '# Docker: manage container nets separately\n';
      }
    }
    
    script += '\nblock in all\npass out all keep state\nEOF_PF\n\n';
    script += 'sudo install -d /etc/pf.anchors\nsudo cp "$TMP_ANCHOR" "$ANCHOR"\n\n';
    script += 'if ! grep -q \'anchor "com.cyberlifecoach"\' /etc/pf.conf; then\n';
    script += '  echo \'anchor "com.cyberlifecoach"\' | sudo tee -a /etc/pf.conf >/dev/null\n';
    script += '  echo \'load anchor "com.cyberlifecoach" from "/etc/pf.anchors/com.cyberlifecoach"\' | sudo tee -a /etc/pf.conf >/dev/null\nfi\n\n';
    script += 'sudo pfctl -nf /etc/pf.conf\nsudo pfctl -f /etc/pf.conf\nsudo pfctl -e || true\n\necho "\\nActive rules:"\nsudo pfctl -sr\necho "\\nDone."\n';
    
    return script;
  };

  const generateWindowsPowerShell = () => {
    const selectedServices = detectSelectedServices();
    const servicesArray = applyRoleDefaults(selectedServices);
    const adminIp = resolveAdminIp();
    
    let script = '# Windows Firewall rules generated by Firewall Rule Generator v4.1.1\r\n';
    script += '$ErrorActionPreference="Stop"\r\n';
    script += 'Set-NetFirewallProfile -Profile Domain,Private,Public -Enabled True -DefaultInboundAction Block -DefaultOutboundAction Allow\r\n';
    script += 'Get-NetFirewallRule -Group "CLC Firewall" -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue\r\n';
    
    if (adminIp) {
      script += `New-NetFirewallRule -DisplayName "CLC Admin SSH 22" -Group "CLC Firewall" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 22 -RemoteAddress ${adminIp} -Profile Any\r\n`;
    }
    
    for (const service of servicesArray) {
      if (service === '53-udp') {
        script += 'New-NetFirewallRule -DisplayName "CLC DNS 53 (UDP)" -Group "CLC Firewall" -Direction Inbound -Action Allow -Protocol UDP -LocalPort 53 -Profile Any\r\n';
      } else if (/^\d+$/.test(service)) {
        script += `New-NetFirewallRule -DisplayName "CLC TCP ${service}" -Group "CLC Firewall" -Direction Inbound -Action Allow -Protocol TCP -LocalPort ${service} -Profile Any\r\n`;
      }
    }
    
    script += 'Set-NetFirewallProfile -LogAllowed True -LogBlocked True -LogFileName "%systemroot%\\system32\\LogFiles\\Firewall\\pfirewall.log"\r\n';
    script += 'Get-NetFirewallRule -Group "CLC Firewall" | Format-Table -AutoSize DisplayName,Direction,Action,Enabled\r\n';
    
    return script;
  };

  const generateWindowsNetsh = () => {
    const selectedServices = detectSelectedServices();
    const servicesArray = applyRoleDefaults(selectedServices);
    const adminIp = resolveAdminIp();
    
    let script = '@echo off\r\n';
    script += 'netsh advfirewall set allprofiles state on\r\n';
    script += 'netsh advfirewall set currentprofile firewallpolicy blockinbound,allowoutbound\r\n';
    script += 'netsh advfirewall firewall delete rule name=all group="CLC Firewall" >nul 2>&1\r\n';
    
    if (adminIp) {
      script += `netsh advfirewall firewall add rule name="CLC Admin SSH 22" group="CLC Firewall" dir=in action=allow protocol=TCP localport=22 remoteip=${adminIp}\r\n`;
    }
    
    for (const service of servicesArray) {
      if (service === '53-udp') {
        script += 'netsh advfirewall firewall add rule name="CLC DNS 53 (UDP)" group="CLC Firewall" dir=in action=allow protocol=UDP localport=53\r\n';
      } else if (/^\d+$/.test(service)) {
        script += `netsh advfirewall firewall add rule name="CLC TCP ${service}" group="CLC Firewall" dir=in action=allow protocol=TCP localport=${service}\r\n`;
      }
    }
    
    script += 'netsh advfirewall set allprofiles logging filename %systemroot%\\system32\\LogFiles\\Firewall\\pfirewall.log\r\n';
    script += 'netsh advfirewall set allprofiles logging maxfilesize 4096\r\n';
    script += 'netsh advfirewall set allprofiles logging droppedconnections enable\r\n';
    script += 'netsh advfirewall firewall show rule name=all group="CLC Firewall"\r\n';
    
    return script;
  };

  const handleGenerate = () => {
    let script = '';
    
    if (targetOs === 'linux') {
      if (firewallType === 'ufw') {
        script = generateUfw();
      } else if (firewallType === 'iptables') {
        script = generateIptables();
      } else if (firewallType === 'nftables') {
        script = generateNftables();
      }
    } else if (targetOs === 'macos') {
      script = generatePfctl();
    } else if (targetOs === 'windows') {
      if (windowsEngine === 'powershell') {
        script = generateWindowsPowerShell();
      } else {
        script = generateWindowsNetsh();
      }
    }
    
    setOutput(script);
    showNotification('Script generated successfully');
  };

  const handleCopy = async () => {
    if (!output) return;
    
    try {
      await navigator.clipboard.writeText(output);
      showNotification('Script copied to clipboard');
    } catch {
      showNotification('Failed to copy to clipboard');
    }
  };

  const handleDownload = () => {
    if (!output) return;
    
    let filename = 'firewall-rules';
    let mimeType = 'text/plain';
    
    if (targetOs === 'linux' || targetOs === 'macos') {
      filename += '.sh';
      mimeType = 'text/x-shellscript';
    } else if (targetOs === 'windows') {
      if (windowsEngine === 'powershell') {
        filename += '.ps1';
        mimeType = 'text/plain';
      } else {
        filename += '.bat';
        mimeType = 'text/plain';
      }
    }
    
    const blob = new Blob([output], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    
    showNotification('Script downloaded');
  };

  const handleReset = () => {
    setTargetOs('linux');
    setFirewallType('ufw');
    setWindowsEngine('powershell');
    setSystemRole('desktop');
    setServices({
      '22': false,
      '80': false,
      '443': false,
      '53-udp': false,
      '3000': false,
      '5000': false,
      'docker': false
    });
    setAllowMyIp(false);
    setIpMode('auto');
    setManualIp('');
    setDetectedIp('');
    setSelectedCountries([]);
    setIncludeIpv6(false);
    setOutput('');
    showNotification('Configuration reset');
  };

  const handleExportProfile = () => {
    const profile = {
      version: 411,
      os: targetOs,
      windowsEngine: windowsEngine,
      firewallType: firewallType,
      systemRole: systemRole,
      services: Object.entries(services).filter(([, checked]) => checked).map(([service]) => service),
      allowMyIp: allowMyIp,
      ipMode: ipMode,
      manualIp: manualIp,
      countries: selectedCountries,
      includeIpv6: includeIpv6
    };
    
    const blob = new Blob([JSON.stringify(profile, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'fw-profile.json';
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    
    showNotification('Profile exported');
  };

  const handleImportProfile = (event) => {
    const file = event.target.files[0];
    if (!file) return;
    
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const profile = JSON.parse(e.target.result);
        
        if (profile.version && profile.version <= 411) {
          setTargetOs(profile.os || 'linux');
          setWindowsEngine(profile.windowsEngine || 'powershell');
          setFirewallType(profile.firewallType || 'ufw');
          setSystemRole(profile.systemRole || 'desktop');
          
          const newServices = { ...services };
          Object.keys(newServices).forEach(key => {
            newServices[key] = (profile.services || []).includes(key);
          });
          setServices(newServices);
          
          setAllowMyIp(!!profile.allowMyIp);
          setIpMode(profile.ipMode === 'manual' ? 'manual' : 'auto');
          setManualIp(profile.manualIp || '');
          setSelectedCountries(profile.countries || []);
          setIncludeIpv6(!!profile.includeIpv6);
          
          showNotification('Profile imported successfully');
        } else {
          showNotification('Unsupported profile version');
        }
      } catch (error) {
        showNotification('Failed to parse profile: ' + error.message);
      }
    };
    reader.readAsText(file);
  };

  const handleServiceToggle = (service) => {
    setServices(prev => ({
      ...prev,
      [service]: !prev[service]
    }));
  };

  const handleCountryToggle = (countryCode) => {
    setSelectedCountries(prev => {
      if (prev.includes(countryCode)) {
        return prev.filter(c => c !== countryCode);
      } else {
        return [...prev, countryCode];
      }
    });
  };

  const getOsNote = () => {
    if (targetOs === 'macos') {
      return 'Generating macOS Packet Filter rules. Country blocking is hidden.';
    } else if (targetOs === 'windows') {
      return 'Generating Windows firewall rules. Pick PowerShell or netsh below.';
    }
    return 'Generating Linux scripts. Switch to macOS or Windows for their native outputs.';
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      {/* Navigation */}
      <nav className="fixed w-full z-50 bg-slate-900/95 backdrop-blur-sm shadow-lg">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-20">
            <a href="/" className="flex items-center space-x-3 group cursor-pointer">
              <img 
                src="/logo.png" 
                alt="CyberLifeCoach" 
                className="h-10 w-auto group-hover:brightness-125 group-hover:scale-110 transition-all duration-300" 
              />
              <span className="text-xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent group-hover:brightness-125 transition-all duration-300">
                CyberLifeCoach
              </span>
            </a>

            <a href="/tools" className="flex items-center space-x-2 text-slate-300 hover:text-cyan-400 transition-colors">
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Tools Hub</span>
            </a>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative pt-32 pb-8 px-4 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-cyan-950/20 to-transparent"></div>
        <div className="absolute inset-0 opacity-20">
          <div className="absolute top-20 left-10 w-72 h-72 bg-cyan-500 rounded-full filter blur-3xl animate-pulse"></div>
        </div>
        
        <div className="relative max-w-7xl mx-auto">
          <div className="flex flex-wrap gap-2 mb-4">
            <span className="text-xs px-3 py-1 rounded-full bg-gradient-to-r from-cyan-500/20 to-blue-500/20 text-cyan-300 border border-cyan-500/30 font-semibold uppercase tracking-wider">
              Security Tool
            </span>
            <span className="text-xs px-3 py-1 rounded-full bg-slate-800 text-slate-400 border border-slate-700">
              Client-Side Only
            </span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-3 bg-gradient-to-r from-white via-cyan-200 to-blue-400 bg-clip-text text-transparent">
            Firewall Rule Generator
          </h1>
          <p className="text-slate-400 text-lg mb-2">
            Generate Linux, macOS, and Windows firewall scripts. Everything runs client side.
          </p>
          <p className="text-sm text-slate-500">Version 4.1.1</p>
        </div>
      </section>

      {/* Main Content */}
      <section className="relative max-w-7xl mx-auto px-4 pb-20">
        <div className="grid lg:grid-cols-3 gap-6">
          {/* Left Column - Configuration */}
          <div className="lg:col-span-2 space-y-6">
            {/* OS Selection */}
            <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-6">
              <h3 className="text-lg font-semibold mb-4 text-cyan-400">Platform</h3>
              
              {/* OS Toggle Buttons */}
              <div className="flex flex-wrap gap-3 mb-4">
                <button
                  onClick={() => setTargetOs('linux')}
                  className={`flex-1 min-w-[120px] px-6 py-3 rounded-lg font-semibold transition-all duration-300 ${
                    targetOs === 'linux'
                      ? 'bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-lg shadow-cyan-500/50'
                      : 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700'
                  }`}
                >
                  <Monitor className="w-4 h-4 inline mr-2" />
                  Linux
                </button>
                <button
                  onClick={() => setTargetOs('macos')}
                  className={`flex-1 min-w-[120px] px-6 py-3 rounded-lg font-semibold transition-all duration-300 ${
                    targetOs === 'macos'
                      ? 'bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-lg shadow-cyan-500/50'
                      : 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700'
                  }`}
                >
                  <Server className="w-4 h-4 inline mr-2" />
                  macOS
                  <span className="ml-2 text-xs px-2 py-0.5 rounded-full bg-cyan-500/20 border border-cyan-500/40">pfctl</span>
                </button>
                <button
                  onClick={() => setTargetOs('windows')}
                  className={`flex-1 min-w-[120px] px-6 py-3 rounded-lg font-semibold transition-all duration-300 ${
                    targetOs === 'windows'
                      ? 'bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-lg shadow-cyan-500/50'
                      : 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700'
                  }`}
                >
                  <Code className="w-4 h-4 inline mr-2" />
                  Windows
                </button>
              </div>

              <p className="text-sm text-slate-400 mb-4">{getOsNote()}</p>

              {/* macOS Hint */}
              {targetOs === 'macos' && (
                <div className="bg-blue-900/20 border border-blue-500/30 rounded-lg p-4 text-sm text-slate-300">
                  macOS uses Packet Filter (pf). This generator creates an anchor-based ruleset and safe commands to validate, load, and enable pf.
                </div>
              )}

              {/* Windows Engine Selection */}
              {targetOs === 'windows' && (
                <div className="mt-4">
                  <label className="block text-sm text-slate-400 mb-2">Engine</label>
                  <select
                    value={windowsEngine}
                    onChange={(e) => setWindowsEngine(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  >
                    <option value="powershell">PowerShell (recommended)</option>
                    <option value="netsh">netsh (classic)</option>
                  </select>
                  <p className="text-xs text-slate-500 mt-2">
                    PowerShell is clearer and easier to maintain. netsh helps with older workflows and GPO copy paste.
                  </p>
                </div>
              )}
            </div>

            {/* General Configuration */}
            <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-6">
              <h3 className="text-lg font-semibold mb-4 text-cyan-400">General</h3>
              
              {/* Linux Firewall Type */}
              {targetOs === 'linux' && (
                <div className="mb-4">
                  <label className="block text-sm text-slate-400 mb-2">Firewall</label>
                  <select
                    value={firewallType}
                    onChange={(e) => setFirewallType(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                  >
                    <option value="ufw">UFW (easy)</option>
                    <option value="iptables">iptables + ipset (country block)</option>
                    <option value="nftables">nftables (modern)</option>
                  </select>
                </div>
              )}

              {/* System Role */}
              <div className="mb-4">
                <label className="block text-sm text-slate-400 mb-2">Role</label>
                <select
                  value={systemRole}
                  onChange={(e) => setSystemRole(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors"
                >
                  <option value="desktop">Desktop / Laptop</option>
                  <option value="webserver">Web Server</option>
                  <option value="developer">Developer / Local Dev</option>
                  <option value="custom">Custom (only selected services)</option>
                </select>
              </div>

              {/* Services */}
              <div className="mb-4">
                <h4 className="font-semibold mb-2">Services / Ports</h4>
                <p className="text-xs text-slate-500 mb-3">Pick services you want to allow (TCP unless noted)</p>
                <div className="grid md:grid-cols-2 gap-2">
                  {Object.keys(services).map(service => (
                    <label key={service} className="flex items-center space-x-3 cursor-pointer group">
                      <input
                        type="checkbox"
                        checked={services[service]}
                        onChange={() => handleServiceToggle(service)}
                        className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-cyan-500 focus:ring-2 focus:ring-cyan-500 focus:ring-offset-0 cursor-pointer"
                      />
                      <span className="text-slate-300 group-hover:text-cyan-400 transition-colors text-sm">
                        {service === '22' && 'SSH (22)'}
                        {service === '80' && 'HTTP (80)'}
                        {service === '443' && 'HTTPS (443)'}
                        {service === '53-udp' && 'DNS (udp 53)'}
                        {service === '3000' && 'Dev (3000)'}
                        {service === '5000' && 'Dev (5000)'}
                        {service === 'docker' && 'Docker (special handling)'}
                      </span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Admin IP */}
              <div>
                <h4 className="font-semibold mb-2">Admin / IP</h4>
                <p className="text-xs text-slate-500 mb-3">Exempt an admin IP so you do not lock yourself out</p>
                
                <label className="flex items-center space-x-3 cursor-pointer group mb-3">
                  <input
                    type="checkbox"
                    checked={allowMyIp}
                    onChange={(e) => setAllowMyIp(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-cyan-500 focus:ring-2 focus:ring-cyan-500 focus:ring-offset-0 cursor-pointer"
                  />
                  <span className="text-slate-300 group-hover:text-cyan-400 transition-colors text-sm">
                    Detect my public IP
                  </span>
                </label>

                <div className="space-y-2">
                  <label className="flex items-center space-x-3 cursor-pointer group">
                    <input
                      type="radio"
                      checked={ipMode === 'auto'}
                      onChange={() => setIpMode('auto')}
                      className="w-4 h-4 border-slate-600 bg-slate-800 text-cyan-500 focus:ring-2 focus:ring-cyan-500 focus:ring-offset-0 cursor-pointer"
                    />
                    <span className="text-slate-300 group-hover:text-cyan-400 transition-colors text-sm">
                      Auto detect
                    </span>
                  </label>

                  <label className="flex items-center space-x-3 cursor-pointer group">
                    <input
                      type="radio"
                      checked={ipMode === 'manual'}
                      onChange={() => setIpMode('manual')}
                      className="w-4 h-4 border-slate-600 bg-slate-800 text-cyan-500 focus:ring-2 focus:ring-cyan-500 focus:ring-offset-0 cursor-pointer"
                    />
                    <span className="text-slate-300 group-hover:text-cyan-400 transition-colors text-sm">
                      Manual
                    </span>
                  </label>

                  <input
                    type="text"
                    value={manualIp}
                    onChange={(e) => setManualIp(e.target.value)}
                    disabled={ipMode !== 'manual'}
                    placeholder="x.x.x.x or x:x::x (only if manual)"
                    className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-2.5 text-slate-300 focus:outline-none focus:border-cyan-500 transition-colors disabled:opacity-50 disabled:cursor-not-allowed text-sm"
                  />
                </div>
              </div>
            </div>

            {/* Country Blocking (Linux only) */}
            {targetOs === 'linux' && (firewallType === 'iptables' || firewallType === 'nftables') && (
              <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-6">
                <h3 className="text-lg font-semibold mb-4 text-cyan-400">Country Blocking</h3>
                <p className="text-sm text-slate-400 mb-4">
                  Select countries to block. Country blocking uses ipset for iptables and native sets for nftables. UFW will skip this feature.
                </p>
                
                <div className="grid md:grid-cols-2 gap-2 mb-4">
                  {countries.map(country => (
                    <label key={country.code} className="flex items-center space-x-3 cursor-pointer group">
                      <input
                        type="checkbox"
                        checked={selectedCountries.includes(country.code)}
                        onChange={() => handleCountryToggle(country.code)}
                        className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-cyan-500 focus:ring-2 focus:ring-cyan-500 focus:ring-offset-0 cursor-pointer"
                      />
                      <span className="text-slate-300 group-hover:text-cyan-400 transition-colors text-sm">
                        {country.name}
                      </span>
                    </label>
                  ))}
                </div>

                <label className="flex items-center space-x-3 cursor-pointer group">
                  <input
                    type="checkbox"
                    checked={includeIpv6}
                    onChange={(e) => setIncludeIpv6(e.target.checked)}
                    className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-cyan-500 focus:ring-2 focus:ring-cyan-500 focus:ring-offset-0 cursor-pointer"
                  />
                  <span className="text-slate-300 group-hover:text-cyan-400 transition-colors text-sm">
                    Attempt IPv6 lists too
                  </span>
                </label>
                <p className="text-xs text-slate-500 mt-2">
                  IPv6 lists may not be available for all providers. The generator will skip gracefully.
                </p>
              </div>
            )}

            {/* Profile Management */}
            <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-6">
              <h3 className="text-lg font-semibold mb-4 text-cyan-400">Profile</h3>
              <div className="flex flex-wrap gap-3 mb-3">
                <button
                  onClick={handleExportProfile}
                  className="flex items-center space-x-2 px-4 py-2.5 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all"
                >
                  <Save className="w-4 h-4" />
                  <span>Export Profile (JSON)</span>
                </button>
                
                <label className="flex items-center space-x-2 px-4 py-2.5 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all cursor-pointer">
                  <Upload className="w-4 h-4" />
                  <span>Import Profile</span>
                  <input
                    type="file"
                    accept="application/json"
                    onChange={handleImportProfile}
                    className="hidden"
                  />
                </label>

                <button
                  onClick={handleReset}
                  className="flex items-center space-x-2 px-4 py-2.5 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all"
                >
                  <RefreshCw className="w-4 h-4" />
                  <span>Reset</span>
                </button>
              </div>
              <p className="text-xs text-slate-500">
                Profiles save OS, engine, firewall type, role, services, countries, IP mode.
              </p>
            </div>

            {/* Action Buttons */}
            <div className="flex flex-wrap gap-3">
              <button
                onClick={handleGenerate}
                className="flex-1 min-w-[200px] bg-gradient-to-r from-cyan-500 to-blue-600 px-6 py-3 rounded-lg font-semibold hover:shadow-lg hover:shadow-cyan-500/50 transition-all duration-300 hover:scale-105 flex items-center justify-center space-x-2"
              >
                <Shield className="w-5 h-5" />
                <span>Generate Script</span>
              </button>
              <button
                onClick={handleCopy}
                disabled={!output}
                className="px-6 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center space-x-2"
              >
                <Copy className="w-5 h-5" />
                <span>Copy</span>
              </button>
              <button
                onClick={handleDownload}
                disabled={!output}
                className="px-6 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center space-x-2"
              >
                <Download className="w-5 h-5" />
                <span>Download</span>
              </button>
              <button
                onClick={() => setShowPreview(!showPreview)}
                className="px-6 py-3 bg-slate-800 hover:bg-slate-700 border border-slate-600 rounded-lg text-slate-300 font-semibold transition-all flex items-center space-x-2"
              >
                {showPreview ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                <span>Toggle Visual Preview</span>
              </button>
            </div>

            {/* Output */}
            <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-6">
              <h3 className="text-lg font-semibold mb-4 text-cyan-400">Generated Script</h3>
              <textarea
                value={output}
                readOnly
                placeholder="Generated script appears here..."
                className="w-full bg-slate-950 border border-slate-700 rounded-lg px-4 py-3 text-slate-300 font-mono text-sm min-h-[400px] focus:outline-none focus:border-cyan-500"
              />
            </div>
          </div>

          {/* Right Column - Visual Preview & Tips */}
          <div className="lg:col-span-1 space-y-6">
            {/* Visual Preview */}
            {showPreview && (
              <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-6">
                <h3 className="text-lg font-semibold mb-4 text-cyan-400">Visual Preview</h3>
                <div className="bg-white rounded-lg p-4">
                  <svg width="100%" height="220" viewBox="0 0 400 220" preserveAspectRatio="xMidYMid meet">
                    <rect x="8" y="8" width="384" height="204" rx="8" fill="#fff" stroke="#e6eef8"/>
                    <text x="200" y="30" fontSize="14" textAnchor="middle" fill="#1d3557">Allowed Ports</text>
                    <g transform="translate(20,40)">
                      {Object.entries(services).filter(([, checked]) => checked).map(([service], i) => {
                        const x = (i % 5) * 72;
                        const y = Math.floor(i / 5) * 28;
                        return (
                          <g key={service}>
                            <rect x={x} y={y} rx="6" ry="6" width="64" height="22" fill="#e6f7f8" stroke="#1d3557"/>
                            <text x={x + 32} y={y + 15} fontSize="12" textAnchor="middle" fill="#073642">{service}</text>
                          </g>
                        );
                      })}
                    </g>
                    <text x="200" y="120" fontSize="14" textAnchor="middle" fill="#b00020">Blocked Countries</text>
                    <g transform="translate(20,135)">
                      {selectedCountries.map((cc, i) => {
                        const country = countries.find(c => c.code === cc);
                        const x = (i % 3) * 120;
                        const y = Math.floor(i / 3) * 22;
                        return (
                          <text key={cc} x={x} y={y + 10} fontSize="12" fill="#a40d2a">{country?.name || cc}</text>
                        );
                      })}
                    </g>
                  </svg>
                </div>
              </div>
            )}

            {/* Quick Tips */}
            <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 p-6">
              <h3 className="text-lg font-semibold mb-4 text-cyan-400">Quick Tips</h3>
              <ul className="space-y-2 text-sm text-slate-400">
                <li className="flex items-start">
                  <span className="text-cyan-400 mr-2">•</span>
                  <span>Always exempt an admin IP before applying DROP policies.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-cyan-400 mr-2">•</span>
                  <span>Test first on a non-critical machine or VM.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-cyan-400 mr-2">•</span>
                  <span>For cloud servers, use the provider console if you get locked out.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-cyan-400 mr-2">•</span>
                  <span>nftables is recommended for new Linux systems. iptables compatibility is still common.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-cyan-400 mr-2">•</span>
                  <span>On macOS, validate with <code className="bg-slate-950 px-1 rounded">pfctl -n</code> before loading.</span>
                </li>
                <li className="flex items-start">
                  <span className="text-cyan-400 mr-2">•</span>
                  <span>On Windows PowerShell, run as Administrator.</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Legal Disclaimer */}
      <section className="max-w-7xl mx-auto px-4 pb-20">
        <div className="bg-slate-900/50 border border-slate-700 rounded-xl p-6">
          <p className="text-sm text-slate-400 leading-relaxed">
            <strong className="text-cyan-400">Legal Disclaimer:</strong> This tool is for educational and informational use only. Generated scripts may alter network access or lock you out of your systems.
            Always review and test outputs in a safe environment. The author and host accept no liability for damage, data loss, or misuse.
            Do not run generated scripts without understanding them.
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-950 border-t border-slate-800 py-12 px-4">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <img 
              src="/logo.png" 
              alt="CyberLifeCoach" 
              className="h-8 w-auto transition-all duration-300 hover:scale-125 hover:brightness-125" 
            />
            <span className="font-bold text-lg transition-all duration-300 hover:text-cyan-400 hover:drop-shadow-[0_0_15px_rgba(34,211,238,0.8)]">
              CyberLifeCoach
            </span>
          </div>
          <div className="text-slate-500 text-sm">
            <p>&copy; {new Date().getFullYear()} CyberLifeCoach</p>
            <p className="text-slate-600">Built for privacy first firewall configuration. Review scripts before running.</p>
            <p>All rights reserved.</p>
          </div>
        </div>
      </footer>

      {/* Notification Toast */}
      {notification && (
        <div className="fixed bottom-8 right-8 bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-6 py-3 rounded-lg shadow-lg shadow-cyan-500/50 animate-fade-in z-50">
          {notification}
        </div>
      )}

      {/* Custom Styles */}
      <style jsx>{`
        @keyframes fade-in {
          from {
            opacity: 0;
            transform: translateY(10px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .animate-fade-in {
          animation: fade-in 0.3s ease-out;
        }
      `}</style>
    </div>
  );
}
